### ISSUE TITLE
sync_close makes it easy to leak FDs

### ISSUE THREAD

**Issue by zanker** [ruby/openssl#11]
The default implementation of OpenSSL is that you wrap the socket, and then if you call `close` on the SSL socket, it doesn't close the underlying one. If you set `sync_close = true` on the SSLSocket, it will call `close` on the underlying socket. Otherwise, you have to do it yourself.

Given you're connecting to a SSL server, I can't think of a situation where you would want to tear down only the SSL portion, and not the underlying socket as well. @tarcieri?

**Comment by rhenium** [comment]
I think it is too late to change the behavior... It may be useful in the most use case, but since I can't examine the impact, I'm afraid this might cause mysterious regressions.

By the way, it looks like sync_close is not mentioned in the documentation at all (!!). I'll add it anyway.
