### ISSUE TITLE
SEGV issue of Ruby CI with Intel C Compiler.

### ISSUE THREAD

**Issue by hsbt** [ruby/openssl#114]
I found segmentation fault in Ruby CI

http://rubyci.org/logs/rubyci.s3.amazonaws.com/icc-x64/ruby-trunk/log/20170301T050002Z.fail.html.gz

If you need to login account of this box, I will create account. Please ping me.

**Comment by rhenium** [comment]
Thanks for letting me know. Apparently this is the issue fixed by https://github.com/ruby/openssl/commit/6693a549d6738e5957201094004abd2159164332. I'll do cherry-pick into the Ruby tree.

**Comment by rhenium** [comment]
Committed as r57750, thanks.
