### ISSUE TITLE
Updating to 2.4 and Cipher key length

### ISSUE THREAD

**Issue by benoittgt** [ruby/openssl#116]
Hello

I've updated my rails app to Rails 4.2.8 and also ruby 2.4. But it breaks on ActiveSupport::MessageEncryptor with cipher key.

```ruby
def encryptor(id)
  ActiveSupport::MessageEncryptor.new(key(id)) # key(id).length = 128
end

def key(id)
  ActiveSupport::KeyGenerator.new(
    Digest::SHA512.base64digest(
      id.to_s + (0...64).map { ('a'..'z').to_a[rand(26)] }.join
    )
  ).generate_key((0...64).map { ('a'..'z').to_a[rand(26)] }.join, 128)
end
```

But when calling `encryptor`

```ruby
     ArgumentError:
       key must be 32 bytes
     # /Users/bti/.rvm/gems/ruby-2.4.0/gems/activesupport-4.2.8/lib/active_support/message_encryptor.rb:79:in `key='
     # /Users/bti/.rvm/gems/ruby-2.4.0/gems/activesupport-4.2.8/lib/active_support/message_encryptor.rb:79:in `_encrypt'
     # /Users/bti/.rvm/gems/ruby-2.4.0/gems/activesupport-4.2.8/lib/active_support/message_encryptor.rb:60:in `encrypt_and_sign'
```

It seems related to : https://github.com/ruby/ruby/commit/ce635262f53b760284d56bb1027baebaaec175d1

Is it possible to have 128 char key?

**Comment by rhenium** [comment]
No. ext/openssl used to simply truncate over-sized keys until r55146. It's demonstrated here: https://gist.github.com/rhenium/b81355fe816dcfae459cc5eadfc4f6f9

**Comment by benoittgt** [comment]
Thanks at lot @rhenium for the fast answer.

**Comment by benoittgt** [comment]
For information.

```ruby
require "openssl"

plain = "ehzjodmftsgplvunkcybwqxrai"
key = "pvuxcxuretmjrnmqjcowwpdwfvtbhtcboixvisconqhuvvpltslsvbhvcijnabxleyijlperumtdduopxzgmxfgaahqhferpqeqqfqunbncjclltefgdjyurdyzbjuzv"

# Ruby 2.3.0
cipher = OpenSSL::Cipher.new("aes-256-cbc").encrypt
cipher.key = key
p cipher.update(plain)
# "\x1D\xC2\xCA@\x9C\xDB5#\x87|\xC5\xD5\xAA\x06\xC7)"

# Ruby 2.4.0
cipher = OpenSSL::Cipher.new("aes-256-cbc").encrypt
cipher.key = key[0..31]
p cipher.update(plain)
# "\x1D\xC2\xCA@\x9C\xDB5#\x87|\xC5\xD5\xAA\x06\xC7)"
```

**Comment by KelseyDH** [comment]
Is there a reason why OpenSSL now requires 16 bytes instead of 16 bytes?  I had to change the above example to:

```ruby
cipher.key = key[0..31]
```

**Comment by biot023** [comment]
@benoittgt 
Thank you, thank you thank you!

**Comment by YaEvan** [comment]
upgrading to ruby2.4+
cipher = OpenSSL::Cipher.new("xxx")
key_len = cipher.key_len
iv_len = cipher.iv_len
cipher.key = key.bytes[0..(key_len-1)].pack( "c" * key_len )
cipher.iv = iv.bytes[0..(iv_len-1)].pack( "c" * iv_len )
