### ISSUE TITLE
Add suppot for X25519

### ISSUE THREAD

**Issue by zedalaye** [ruby/openssl#117]
OpenSSL 1.1 add support for X25519 Eliptic Curve Cryptography. Current release of ruby-openssl gem (v2.0.3) do not seems to support it through PKey::EC

Could/will X25519 support be added to release 2.1 ?

**Comment by Djon13** [comment]
ok

**Comment by rhenium** [comment]
X25519 won't be accessible through OpenSSL::PKey::EC because it's not implemented on top of the EC API. However we currently lack bindings for the EVP API that would be useful for X25519. See #119.

**Comment by ilyacherevkov** [comment]
+1

**Comment by tarcieri** [comment]
In the meantime, I've released an X25519 gem which provides a highly optimized X25519 implementation: https://github.com/cryptosphere/x25519

**Comment by ioquatix** [comment]
@tarcieri do you know where we got with this?

**Comment by tarcieri** [comment]
Nope
