### ISSUE TITLE
ArgumentError: Could not parse the PKCS7: nested asn1 error

### ISSUE THREAD

**Issue by BjornMelgaard** [ruby/openssl#120]
Got [this](https://bugs.ruby-lang.org/issues/12162) error on ruby-2.4.0

example
```
p7chain = OpenSSL::PKCS7.new
p7chain.type = 'signed'
p7chain.certificates = [@certificate, subca_cert]
OpenSSL::PKCS7.new(p7chain.to_s)

ArgumentError: Could not parse the PKCS7: nested asn1 error
```

Am I doing all right, docs are mysterious  in this regard?

**Comment by rhenium** [comment]
The structure is incomplete and thus invalid. Could you elaborate more?

**Comment by BjornMelgaard** [comment]
Yes, root is issuer of subca, subca is issuer of `@certificate`

`[1] pry(#<CreateFromCsr>)> @certificate.verify subca_cert.public_key`

pkcs7 structure is created [here](https://github.com/BjornMelgaard/certificate_authority/blob/master/app/commands/create_from_csr.rb#L10), and cannot be restored [here](https://github.com/BjornMelgaard/certificate_authority/blob/master/spec/controllers/api/v1/certificates_controller_spec.rb#L14)

**Comment by rhenium** [comment]
I meant it's incomplete in that the example code you showed did not set the main part of the PKCS#7 SignedData structure, the content to be signed.

You still have to set something to make it valid as a PKCS#7 structure, even if you are using it just as a certificate store. Maybe an empty String can be passed to OpenSSL::PKCS7#data=[*], I didn't test though.

[*]: http://ruby.github.io/openssl/OpenSSL/PKCS7.html#method-i-data-3D
