### ISSUE TITLE
SSLSocket :hostname= accessor removed

### ISSUE THREAD

**Issue by andrew-aladev** [ruby/openssl#121]
Hello. Some websites will force you to use SNI. For example "httpbin.org".

```
openssl s_client -connect httpbin.org:443
> tlsv1 alert internal error
```

```
openssl s_client -connect httpbin.org:443 -servername httpbin.org
> ok
```

```
require "openssl"
require "socket"

HOST = "httpbin.org"

class SSL < OpenSSL::SSL::SSLSocket
  def initialize *args
    super
    @hostname = HOST
  end
end

socket = TCPSocket.open HOST, 443

begin
  ssl_socket = SSL.new socket, OpenSSL::SSL::SSLContext.new

  begin
    ssl_socket.connect
    puts "connected"
  ensure
    ssl_socket.close
  end

ensure
  socket.close
end
```

This code works fine with any **ruby 2.0-2.3** and **rubinius**, but it failed with **ruby 2.4.0-2.4.1**.

I can see that you've removed accessor from **lib/ruby/2.4.0/openssl/ssl.rb**:

```
if ExtConfig::HAVE_TLSEXT_HOST_NAME
  attr_reader :hostname
end
ext/openssl/ossl_ssl.c:
```

```
#ifdef HAVE_SSL_SET_TLSEXT_HOST_NAME
    /* #hostname is defined in lib/openssl/ssl.rb */
    rb_define_method(cSSLSocket, "hostname=", ossl_ssl_set_hostname, 1);
#endif
```

So we have to use **self.hostname = HOST** instead of **@hostname = HOST**.

Please add this new behaviour in documentation. Thank you.

https://bugs.ruby-lang.org/issues/13401

**Comment by andrew-aladev** [comment]
This is related to the commit https://github.com/ruby/openssl/commit/998d66712a78c623977db37fc8c6f95502b71d3c by @rhenium.

**Comment by rhenium** [comment]
As I wrote at the Ruby issue tracker, the accessor methods OpenSSL::SSL::SSLSocket#{hostname,hostname=} *do* exist in Ruby 2.4 (or, openssl gem v2.0) as they did in previous versions of Ruby. Modifying the instance variable directly was never a feature.

**Comment by andrew-aladev** [comment]
@rhenium, Hello. It was `rb_iv_get(self, "@hostname")` in `ossl_ssl_setup`. Ok. We will use new writer. Thank you.
