### ISSUE TITLE
Testing ruby-head and OpenSSL 1.1 on Travis

### ISSUE THREAD

**Issue by junaruga** [ruby/openssl#123]
Hello,

Recently we got new test case for `ruby-head` and OpenSSL 1.0.1f [1] that is installed to Ubuntu as default by the PR #122 

https://travis-ci.org/ruby/openssl/jobs/233083194
> $ rake test
> /home/travis/.rvm/rubies/ruby-head/bin/ruby -I./lib -ropenssl -ve'puts OpenSSL::OPENSSL_VERSION, OpenSSL::OPENSSL_LIBRARY_VERSION'
> ...
> OpenSSL 1.0.1f 6 Jan 2014

I like this test case.
However I think that this is not enough to catch the issue of `ruby-head`.
I also want a test case for `ruby-head` and OpenSSL 1.1 (1.1 latest stable version) on Travis test too.

Anyone, do you have any idea to implement this?

Is it possible that after installing OpenSSL 1.1.0e from source code, then installed rvm: `ruby-head` will use the OpenSSL?

**Comment by rhenium** [comment]
> Is it possible that after installing OpenSSL 1.1.0e from source code, then installed rvm: ruby-head will use the OpenSSL?

It is possible of course, with several extra minutes of running time, but I doubt if it expands test coverage.

We are already running the test suite with the combination of OpenSSL 1.1.0 and Ruby 2.4 and with the combination of Ubuntu's OpenSSL and Ruby trunk (which is added this time). I think this is good enough.

**Comment by junaruga** [comment]
All right. I see it.
If the test case does not expand the test coverage effectively, adding the test case does not make sense.
