### ISSUE TITLE
OpenSSL 1.10f and OpenSSL::SSL::SSLContext::METHODS

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/openssl#124]
I'm a Windows type and working with (and testing) MinGW builds on trunk, along with testing `gem install` of extension gems.

So, I built EventMachine with OpenSSL.  I've build several versions of EM (local use with Thin), but never added OpenSSL.  With OpenSSL, EM builds, runs fine with Thin as a local server, and verifies a server, but, it fails several tests.

The OpenSSL MinGW package passes all tests, and Ruby trunk passes all `test-all` OpenSSL tests.

So, I was led to ask [EventMachine Issue 786](https://github.com/eventmachine/eventmachine/issues/786).  I not sure where the issue is - EventMachine, Ruby OpenSSL ext std-lib, OpenSSL package, or my lack of OpenSSL knowledge.

I think the question is - why is Ruby OpenSSL ext including `:SSLv23`, `:SSLv23_server`, and `:SSLv23_client` in `OpenSSL::SSL::SSLContext::METHODS` when they are not supported by the build of OpenSSL package that I'm using (OpenSSL 1.1.0f stable from 2017-03-15)?

Or, what am I unaware of or not understanding?  TIA.

**Comment by rhenium** [comment]
The SSLv23_method(3) manpage says:

> SSLv23_method(), SSLv23_server_method(),
> SSLv23_client_method()
>     These are the general-purpose version-flexible
>     SSL/TLS methods.  The actual protocol version used
>     will be negotiated to the highest version mutually
>     supported by the client and the server.  The
>     supported protocols are SSLv2, SSLv3, TLSv1,
>     TLSv1.1 and TLSv1.2.  Most applications should use
>     these method, and avoid the version specific
>     methods described below.
