### ISSUE TITLE
OpenSSL::TestSSL#test_sslctx_set_params fails in recent Fedora

### ISSUE THREAD

**Issue by voxik** [ruby/openssl#127]
The Fedora builds of Ruby 2.4.1 recently started to fail [[1]] with following error:

~~~
  1) Failure:
OpenSSL::TestSSL#test_sslctx_set_params [/builddir/build/BUILD/ruby-2.4.1/test/openssl/test_ssl.rb:353]:
weak ciphers are disabled
~~~

This is apparently due to this commit to OpenSSL [[2]]. This commit enables 3DES, which according to this [[3]] report might be the best option available on some WiFi routers. According to Fedora OpenSSL maintainer @t8m, this is going to be permanent change for the foreseeable future.

I am doing to patch this specific test to make it pass on recent Fedora, but I would appreciate if there was some generic way to get this working without local patches.

[1]: https://apps.fedoraproject.org/koschei/build/2976771
[2]: http://pkgs.fedoraproject.org/cgit/rpms/openssl.git/commit/?id=81258b6d2af1ad43f5a18b352730c041795a7137
[3]: https://bugzilla.redhat.com/show_bug.cgi?id=1453066

**Comment by rhenium** [comment]
I modified that test to ignore 3DES cipher suites. Thanks for the report!

**Comment by voxik** [comment]
Thx. The patch helps.
