### ISSUE TITLE
Add support for `openssl ocsp -header HOST URL`

### ISSUE THREAD

**Issue by pgporada** [ruby/openssl#129]
Per https://github.com/openssl/openssl/commit/1f234f71357a6bac7b8b2a54649c07bfe55e9c39, upstream openssl ocsp client supports the `-header HOST URL` flag. I have a need to use this functionality for a monitoring script, but can't for the life of me figure out how to use `OpenSSL::OCSP` to accept the custom header .

I've got my shell command recreated in ruby except for the header flag.
```
openssl ocsp \
    -issuer ${ISSUER}.crt \
    -cert ${CLIENT}.crt \
    -CAfile ${ISSUER}.crt \
    -url http://ocsp.whatever.com \
    -header "HOST" "ocsp.whatever.com"
```

For more context, please see https://blog.ivanristic.com/2014/02/checking-ocsp-revocation-using-openssl.html

Thanks for the eyes and any help with this.

**Comment by rhenium** [comment]
OpenSSL::OCSP doesn't have a facility to actually an OCSP request over HTTP. See the docs: http://ruby.github.io/openssl/OpenSSL/OCSP.html
