### ISSUE TITLE
Question re: RSA#to_pem

### ISSUE THREAD

**Issue by etdsoft** [ruby/openssl#13]
I've been doing some code spelunking looking into how `#to_pem(cipher, key)` is implemented.

It looks like `#to_pem` is an alias to `#export` calling the C  `PEM_write_bio_RSAPrivateKey` API (from [here](http://ruby-doc.org/stdlib-2.1.5/libdoc/openssl/rdoc/OpenSSL/PKey/RSA.html#method-i-export)).

[The OpenSSL docs](https://www.openssl.org/docs/crypto/pem.html#PEM-ENCRYPTION-FORMAT) discourage using this method as the key is derived using a single pass of the hash function and recommend using `PEM_write_bio_PKCS8PrivateKey` instead.

However going to the OpenSSL source, the method definition:

```
int PEM_write_bio_PrivateKey(BIO *bp, EVP_PKEY *x, const EVP_CIPHER *enc,
                             unsigned char *kstr, int klen,
                             pem_password_cb *cb, void *u)
{
    char pem_str[80];
    if (!x->ameth || x->ameth->priv_encode)
        return PEM_write_bio_PKCS8PrivateKey(bp, x, enc,
                                             (char *)kstr, klen, cb, u);

    BIO_snprintf(pem_str, 80, "%s PRIVATE KEY", x->ameth->pem_str);
    return PEM_ASN1_write_bio((i2d_of_void *)i2d_PrivateKey,
                              pem_str, bp, x, enc, kstr, klen, cb, u);
}
```

Seems to use `x->ameth` to in some case upgrade the call to the PKCS8 version.

So my question is, what happens when you do:

```
keypair.to_pem(cipher, pk_passphrase)
```

Is a count of 1 used to derive the key (old-style `_PrivateKey` functions) or a count of 2048 (new style `_PKCS8PrivateKey` functions)?

I assumed it was 1, and tried verifying it with `pkcs5_keyivgen` and a count of 1 (`pkcs5_keyivgen` ends up calling the C `EVP_BytesToKey` which I understand is the same function used by `#export`), but that didn't work.

```
puts "--Decrypting--"
dec = OpenSSL::Cipher::Cipher.new('aes-128-cbc')
dec.decrypt
dec.pkcs5_keyivgen(pk_passphrase, salt, 1)
dec.iv = 'D33CBFE1DB5FDBBCBEEE6A06'.scan(/../).map { |x| x.hex.chr }.join
plain =  dec.update(cipher)
plain << dec.final
puts %(decrypted text: "#{plain}")
puts
```

**Comment by rhenium** [comment]
You may have already figured out, but just for the record.

PEM_write_bio_RSAPrivateKey() which we call from OpenSSL::PKey::RSA#export has nothing to do with PEM_write_bio_PrivateKey(). PEM_write_bio_RSAPrivateKey() ends up calling PEM_ASN1_write_bio() and should do PBKDF1 with an iteration count of 1.
