### ISSUE TITLE
Unable to install with gem

### ISSUE THREAD

**Issue by binarykitchen** [ruby/openssl#130]
```
michael.heuberger@binarykitchen /v/l/g/2/gems ❯❯❯ gem install openssl
ERROR:  Loading command: install (LoadError)
        libssl.so.1.0.2: cannot open shared object file: No such file or directory - /var/lib/gems/2.4.0/gems/openssl-2.0.4/lib/openssl.so
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
```

Any ideas why?

**Comment by binarykitchen** [comment]
Btw using this ruby version

```
michael.heuberger@binarykitchen /v/l/g/2/gems ❯❯❯ ruby -v                                                                                                                             ⏎
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux-gnu]
```

**Comment by rhenium** [comment]
`gem install` itself wants openssl for HTTPS. Supposedly you have removed OpenSSL 1.0.2 from the system after installing the currently installed openssl gem.

**Comment by binarykitchen** [comment]
Sorry @rhenium but I do not understand what to do - I did not remove OpenSSL recently. So must be something else ...

**Comment by rhenium** [comment]
Upgrading OpenSSL to an ABI-incompatible version (1.1.0) has the same effect. Anyway this doesn't seem to be an issue inside the openssl gem.

**Comment by dikiaap** [comment]
I have same error after updating OpenSSL. Try running this command.

```shell
find / -iname openssl.so
# Mine is in /usr/lib/i386-linux-gnu/ruby/2.4.0/openssl.so
sudo rm -rf /var/lib/gems/2.4.0/gems/openssl-2.0.4/lib/openssl.so
sudo ln -s /usr/lib/i386-linux-gnu/ruby/2.4.0/openssl.so /var/lib/gems/2.4.0/gems/openssl-2.0.4/lib/openssl.so`
```

**Comment by rhenium** [comment]
@dikiaap Please don't. The extension needs to be recompiled and [`gem pristine`](http://guides.rubygems.org/command-reference/#gem-pristine) will do the job.
