### ISSUE TITLE
Add 2.4 (1.0.2k) & trunk (1.1.0f) to appveyor?

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/openssl#132]
See [Appveyor MSP-Greg/openssl](https://ci.appveyor.com/project/MSP-Greg/openssl) for test results.  Does take a little...

Note - I accidentally left a line in the yml file that prints all the MSYS2 / MinGW packages (only for trunk build), I'll remove if people would like me to PR it...

**Comment by rhenium** [comment]
As for Ruby 2.4 (from RI2), it is tested already: 26f928baa819cf06a3efd435a8ec28731d1da3f8. Testing against Ruby trunk and OpenSSL 1.1 might be also helpful, but I prefer, rather strongly, not to compile them ourselves.

**Comment by MSP-Greg** [comment]
@rhenium

> As for Ruby 2.4 (from RI2), it is tested already: 26f928b.

Sorry for missing the commit on the maint branch.

>  but I prefer, rather strongly, not to compile them ourselves.

I don't understand, especially the 'rather strongly' or 'ourselves'.  I'd be happy to do my builds on Appveyor, but they're a lot faster on my desktop...

I guess if there are OpenSSL errors, I'll see them when they're pushed to trunk.  Feel free to to use my build or my packages.
