### ISSUE TITLE
Gem, Ruby and OpenSSL versions

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/openssl#133]
The current release of the openssl gem (2.0.4) supports Ruby 2.3.  It also supports OpenSSL 1.1.0.

**Question**

If someone does 'gem update' (and hence, updates Ruby OpenSSL), is there a recommendation for whether 1.1.0 or 1.0.2 should be used with Ruby 2.3 or Ruby 2.4?

Or, is the issue more a matter of whether one's code is dependent on any gems that are not compatible with Ruby 2.4, and hence, may not be compatible with Ruby OpenSSL v2+?

**Background**

Over in windows (mingw) world, there have been a few posts by people who (understandably) do a `gem update --system`, followed by `gem update`.

Since the base dll's required are embedded in the Ruby folder structure (`bin/ruby_builtin_dlls`), but the files used for compiling are in the msys64 folder/app, the possibility exists for some issues. Additionally, I believe there are a few gems that compile using OpenSSL.

I have read thru [Bug #12324 - Support OpenSSL 1.1.0 (and drop support for 0.9.6/0.9.7)](https://bugs.ruby-lang.org/issues/12324).

FWIW, Re MinGW builds, I may investigate how hard it would be to perform `gem update --system` and `gem update` on a build, then push the code back into the build as if the updates were the original default gems (along with updating any required dll's, etc).  As it should be, default gems seem to be on a bit slower release schedule than bundled gems (of which none currently are extension gems)...

Thanks in advance.

**Comment by rhenium** [comment]
There isn't. Any combination of the versions should work nicely. But, in general, having two different versions of OpenSSL loaded from one process tends to cause issues. I'd personally recommend letting `gem update` use the system defaults, in other words, specifying no `--with-{opt,openssl}-*` options at all.

I'm afraid I don't understand what is the issue in mingw builds correctly. Do you mean RI2(?) has a custom OpenSSL DLLs in PATH with higher precedence than the ones installed by `pacman mingw-w64-foo-openssl'?

**Comment by MSP-Greg** [comment]
First of all, sorry for being unclear.  By 'RI2', I'm referring to RubyInstaller2, which is the successor to RubyInstaller.

As an aside, I don't think RI2 is technically using PATH, it's using a windows specific means of setting a library/dll path.

> I'm afraid I don't understand what is the issue in mingw builds correctly.

RI2 builds (like old RI builds) are stand-alone, in the sense that no MSYS2/MinGW files/tools need to be installed for ruby to run with the std-lib.  Hence, there are dll files included.  Obviously, MSYS2/MinGW files/tools need to be installed to build extension gems.

At present, I'm not sure what the precedence is, but I suspect the dll's included with the build have it.

I'm also not sure if packages always maintain API compatibility as they're updated (without file name changes).  Because of that, which should have higher precedence is somewhat unclear.

But as you mentioned, one could have have EventMachine built with OpenSSL 1.1.0, and Ruby OpenSSL build with 1.0.2, or, vice versa,..

As you know, windows shields users from these kind of issues, and I assume OSX does the same.

Lastly, you mentioned the word 'custom'.  At present, RI2 uses only MSYS2/MinGW packages.  While RI2 was coming into existence, I had been building using the same toolset.  I found the GDBM 1.12 package didn't work, and the OpenSSL packages were staying in the 1.0.2 branch.  Hence, I have two custom packages that I use in my builds.

My main reason for building was to see if I could get consistent test-all results with trunk, as test-all had been an issue in the past.  As you know, test-all was only recently added to trunk appveyor mswin testing.  Without consistent results, it's kind of difficult to file a bug report over a commit.  I've also been using trunk for quite a while...

Thanks again.   It's good to know that Ruby 2.3 will work with Ruby OpenSSL 2.04 and OpenSSL 1.1.0...

**Comment by rhenium** [comment]
Thanks for explaining. [I can't test that right now, but] it could still be a problem and should be fixed by RI2, if user-installed-gems find DLLs that are included in RI2. There can be symbol additions between letter versions and thus nobody guarantees gems compiled against OpenSSL 1.0.2l works properly with 1.0.2k DLLs.

One approach would be to make the stdlibs statically link to OpenSSL so RI2 won't have to include those DLLs.

**Comment by MSP-Greg** [comment]
In some respects, I keep thinking that there is no good solution at present, especially one that doesn't hinder advanced users and also protect new users.  I wish I knew more about how all the flavors of *nix handle these issues, or even systems like .NET or NPM.

> One approach would be to make the stdlibs statically link to OpenSSL so RI2 won't have to include those DLLs.

That might be a good start, but doesn't it have to potential to 'break' if a new std-lib gem is released and installed?  One solution might be to have everything (gems, std-lib, etc) statically link, but that seems rather extreme and very difficult to implement. 

I think the root issue is the fact that we're using dll's in the MSYS2/MinGW system both for build and runtime.  I also think it's unfair to presume that the only reason a user has MSYS2/MinGW installed is for ruby use.  Maybe a solution is to somehow decouple the runtime use from build use, but I can't think of an easy way to do so.  It would (obviously) involve some means of collecting and updating ruby dll dependencies in a folder separate from MSYS2/MinGW.

As an aside, I'm glad to see that the std-lib is being 'gemified', but when I first heard about it I couldn't help but think that the first ones to be 'gemified' should be extension std-lib's with dependencies.  While working on a ruby_2_3 build, I had problems with `digest` being native code and `openssl` being 'gemified' (see [issue #13771](https://bugs.ruby-lang.org/issues/13771), I didn't mention this issue because I didn't want to involve you without asking.)

Getting back to Ruby OpenSSL, I built ruby_2_3 with 1.0.2 and ruby_2_4 with 1.1.0.  Then I installed / updated the openssl gem to 2.0.4 using 1.1.0.  All tests (test and spec) passed in both branch builds.  As mentioned, I did have to manually shove a 1.1.0 build of std-lib digest back into ruby_2_3...

**Comment by MSP-Greg** [comment]
@rhenium

Thanks for your thoughts and all your work.  I know you don't like 'non cloud builds', but I've got ruby_2_3 and ruby_2_4 builds with 1.1.0 available.  Info [here](https://msp-greg.github.io/file.mingw_builds.html).

See [oneclick/rubyinstaller2 Issue #59](https://github.com/oneclick/rubyinstaller2/issues/59).  I'm proposing that all dll's used for installing/updating gems be copied to `bin\ruby_builtin_dlls` for MinGW builds.  Hence, ruby & gem runtime dll's could all be found inside of the main ruby folder.
