### ISSUE TITLE
Revisiting the 4 byte password length enforcement for decrypting PEM key material

### ISSUE THREAD

**Issue by cimnine** [ruby/openssl#136]
In Ruby 2.3, it was possible to prevent OpenSSL prompting for the PEM's password on the command line by feeding it an empty password. If the PEM was encrypted, it would result in the same error as when a wrong password was provided. If the PEM wasn't encrypted, it would read the PEM just fine.

```ruby
#!/usr/bin/env ruby2.3
OpenSSL::PKey::RSA.new File.read('unencrypted_key.pem')       # works just fine
OpenSSL::PKey::RSA.new File.read('unencrypted_key.pem'), ''   # works equally well
OpenSSL::PKey::RSA.new File.read('encrypted_key.pem')         # OpenSSL will ask on the console "Enter PEM pass phrase:" and block the thread.
OpenSSL::PKey::RSA.new File.read('encrypted_key.pem'), ''     # will result in an OpenSSL::PKey::RSAError
OpenSSL::PKey::RSA.new File.read('encrypted_key.pem'), 'key1' # given 'key1' is the correct password, this works just fine
```

Since Ruby 2.4, the Ruby OpenSSL abstraction prevents passwords shorter than 4 bytes to be used to encrypt, *but also to decrypt*, PEM files. This breaks the behaviour described above. When no password is given for a PEM file, but that file's content is encrypted, OpenSSL can now not be prevented anymore from asking on the terminal for the key and thous blocking the thread. In a server environment this is not helpful behaviour.

```ruby
#!/usr/bin/env ruby2.4
OpenSSL::PKey::RSA.new File.read('unencrypted_key.pem')       # works just fine
OpenSSL::PKey::RSA.new File.read('unencrypted_key.pem'), ''   # fails with OpenSSL::OpenSSLError, "password must be at least 4 bytes"
OpenSSL::PKey::RSA.new File.read('encrypted_key.pem')         # OpenSSL will BLOCK THE THREAD and ask on the console "Enter PEM pass phrase:".
OpenSSL::PKey::RSA.new File.read('encrypted_key.pem'), ''     # fails with OpenSSL::OpenSSLError, "password must be at least 4 bytes"
OpenSSL::PKey::RSA.new File.read('encrypted_key.pem'), 'key1' # given 'key1' is the correct password, this works just fine
```

As long as it is known whether incoming PEM data is encrypted or unencrypted, it can perfectly work around the new situation. But if PEM data is provided, of which it is unknown whether it's encrypted or not, and the user does not provide a password, the application might get blocked by OpenSSL:

```ruby
#!/usr/bin/env ruby2.4
user_provided_password = ''
begin
  if user_provided_password.nil? || user_provided_password.bytesize < 4
    OpenSSL::PKey::RSA.new user_provided_key
    # Key was not encrypted: good
    # Key was encrypted: OpenSSL will BLOCK THE THREAD and ask on the console "Enter PEM pass phrase:"
  else
    OpenSSL::PKey::RSA.new user_provided_key, user_provided_password
  end
rescue OpenSSL:PKey::RSAError
  raise "Wrong password"
end
```

Whereas before, by simply passing `''` it would only be required to deal with the `OpenSSL::PKey::RSAError` and the application could not get stuck.

```ruby
#!/usr/bin/env ruby2.3
user_provided_password = ''
user_provided_key = File.read('user_provided_key.pem')
begin
  if user_provided_password.nil? || user_provided_password.empty?
    OpenSSL::PKey::RSA.new user_provided_key, ''
    # Key was not encrypted: good
    # Key was encrypted: good, OpenSSL::PKey::RSAError is raised. I can handle that.
  else
    OpenSSL::PKey::RSA.new user_provided_key, user_provided_password
  end
rescue OpenSSL::PKey::RSAError
  raise "Wrong password"
end
```

My suggestion is to cease enforcing the 4 byte limit when *decrypting* PEM encoded data. It's implicitly enforced anyway, because any key below 4 bytes will not be able to decrypt PEM data, that is encrypted, anyway.

In the meantime, I'd be happy to hear some suggestions about detecting whether the key material in a PEM string is encrypted or unencrypted *before* handing it over to OpenSSL.

**Comment by rhenium** [comment]
The 4 bytes limit has been removed by https://github.com/ruby/openssl/commit/a896c3d1dfa090e92dec1abf8ac12843af6af721. Can you try with openssl gem v2.0.5?

**Comment by cimnine** [comment]
This is great! Thanks a lot for pointing it out to me, I didn't realise the OpenSSL code is also shipped independently of Ruby as gem.
