### ISSUE TITLE
OpenSSL::TestPKeyRSA#test_pem_passwd password length error

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/openssl#137]
When running tests against 1.1.0f, I came across the error message
```
OpenSSL::OpenSSLError: password must be at least 4 bytes
```
in [OpenSSL::TestPKeyRSA#test_pem_passwd](https://github.com/ruby/openssl/blob/3ed3fc5dde962615fcf42d0cfa4feba6cb8af9d5/test/test_pkey_rsa.rb#L246-L255)

I changed all occurrences of 'key' to 'key1', and it passed.  I'd submit a PR, but not sure if it should be version specific...

**Comment by rhenium** [comment]
That's strange, because it can't happen anymore (https://github.com/ruby/openssl/commit/a896c3d1dfa090e92dec1abf8ac12843af6af721). How did you run the tests?

**Comment by MSP-Greg** [comment]
I apologize.  I was running tests on some 2.3 and 2.4 builds I did recently, and then installed a few default extension gems.  Some were with 1.1.0f, and some were with 1.0.2l.

I thought it odd, but I was getting interrupted a lot.   The build with the failure was done with 2.0.4, two days before 2.0.5 was released.

Sorry, and thanks again...
