### ISSUE TITLE
2.1.0.beta1 vs 2.0.5 with 1.1.0f - SSLContext::METHODS change

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/openssl#147]
I'm somewhat in the middle of some other coding tasks, but I just noticed that

when using 2.1.0.beta1, SSLContext::METHODS is contains
```
SSLv2 SSLv23 SSLv3 TLSv1 TLSv1_1 TLSv1_2
```
when using 2.0.5, SSLContext::METHODS contains
```
SSLv23 TLSv1 TLSv1_1 TLSv1_2
```

Note that `SSLv2` and `SSLv3` appear in 2.1.0 but not 2.0.5.  I'm using 1.1.0f, and I thought the OpenSSL package was build with SSL disabled.  I run a daily Appveyor with info helpful for Ruby, the trunk builds are all the way at the bottom.  See the OpenSSL section, 2.1.0.beta1 [here](https://ci.appveyor.com/project/MSP-Greg/appveyor-ruby/build/1.0.94) and 2.0.5 [here](https://ci.appveyor.com/project/MSP-Greg/appveyor-ruby/build/1.0.92).

I checked History.md, the only thing I saw related to SSLContext::Methods was 'OpenSSL::SSL::SSLContext#min_version= and #max_version= are added. [GitHub #142]'

Not super knowledgeable about SSL, but this seems kind of odd...

EDIT: Just found some notes:

1.1.0f package used for above builds (shows no SSL versions):
```
>openssl ciphers -help
Usage: ciphers [options]
Valid options are:
 -help    Display this summary
 -v       Verbose listing of the SSL/TLS ciphers
 -V       Even more verbose
 -s       Only supported ciphers
 -tls1    TLS1 mode
 -tls1_1  TLS1.1 mode
 -tls1_2  TLS1.2 mode
 -psk     include ciphersuites requiring PSK
 -srp     include ciphersuites requiring SRP
```

Same command with a 1.0.2l package (shows SSLv2 & SSLv3):
```
>openssl ciphers -help
usage: ciphers args
 -v          - verbose mode, a textual listing of the SSL/TLS ciphers in OpenSSL
 -V          - even more verbose
 -ssl2       - SSL2 mode
 -ssl3       - SSL3 mode
 -tls1       - TLS1 mode
```

**Comment by MSP-Greg** [comment]
I just came across [ssl: rework SSLContext#ssl_version=](https://github.com/ruby/openssl/commit/5653599e150bd92d8631858fe6e0def1f9a3c33d), so I'll close this, since I haven't had time to look thru...

**Comment by MSP-Greg** [comment]
After reviewing the commit, and the added methods in SSLContext, I believe that SSLContext::METHODS should remain.

For instance, I have seen it used in test scripts to determine what tests to run, as it allows one to easily determine whether the OpenSSL library supports various SSL/TLS methods.

**Comment by rhenium** [comment]
I probably should have mentioned the change in SSLContext#ssl_version= and SSLContext::METHODS in History.md. I'll try when I make 2.1.0.beta2 release.

The change itself is perfectly expected. The constant contains symbol values that would be accepted by SSLContext#ssl_version=, so the semantics did not change. In fact, checking the constant has never been a proper way to check whether an SSL/TLS protocol version is supported by the OpenSSL library or not -- with previous versions of ext/openssl, one could build OpenSSL with the TLSv1{,_client,_server} methods enabled and no actual TLS 1.0 support.
