### ISSUE TITLE
Ultrahook ssl issue

### ISSUE THREAD

**Issue by emre141** [ruby/openssl#152]
Hi

I am also my testing environment on my local virtualbox that is running Openshift platform and a defined my github account a webhook and to communicate both them configure ultrahook but there is a redirect traffic from payload url to private unsecure (https.//private_network/8443/oapi/v1/names paces/third/buildconfigs/php/webhooks/4f940a9e-6281-4f08-9386-a1ccfeb12bca/githu b) but i have get a ruby openssl issue as below

D:/Ruby24-x64/lib/ruby/2.4.0/openssl/buffering.rb:182:in sysread_nonblock': An existing connection was forcibly closed by the remote host. (Errno::ECONNRESET) from D:/Ruby24-x64/lib/ruby/2.4.0/openssl/buffering.rb:182:inread_nonb lock'
from D:/Ruby24-x64/lib/ruby/2.4.0/net/protocol.rb:172:in rbuf_fill' from D:/Ruby24-x64/lib/ruby/2.4.0/net/protocol.rb:154:inreaduntil'
from D:/Ruby24-x64/lib/ruby/2.4.0/net/protocol.rb:164:in readline' from D:/Ruby24-x64/lib/ruby/2.4.0/net/http/response.rb:40:inread_statu s_line'
from D:/Ruby24-x64/lib/ruby/2.4.0/net/http/response.rb:29:in read_new' from D:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:1446:inblock in transpor t_request'
from D:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:1443:in catch' from D:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:1443:intransport_request '
from D:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:1416:in request' from D:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:1409:inblock in request'
from D:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:877:in start' from D:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:1407:inrequest'
from D:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:1430:in send_entity' from D:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:1218:inpost'
from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ultrahook-0.1.4/lib/ultrahoo k/client.rb:127:in http_post' from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ultrahook-0.1.4/lib/ultrahoo k/client.rb:116:inprocess_request'
from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ultrahook-0.1.4/lib/ultrahoo k/client.rb:90:in process' from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ultrahook-0.1.4/lib/ultrahoo k/client.rb:160:inblock (3 levels) in init_stream'
from D:/Ruby24-x64/lib/ruby/2.4.0/net/protocol.rb:429:in call_block' from D:/Ruby24-x64/lib/ruby/2.4.0/net/protocol.rb:420:in<<'
from D:/Ruby24-x64/lib/ruby/2.4.0/net/protocol.rb:126:in read' from D:/Ruby24-x64/lib/ruby/2.4.0/net/http/response.rb:321:inread_chun ked'
from D:/Ruby24-x64/lib/ruby/2.4.0/net/http/response.rb:285:in block in read_body_0' from D:/Ruby24-x64/lib/ruby/2.4.0/net/http/response.rb:278:ininflater'
from D:/Ruby24-x64/lib/ruby/2.4.0/net/http/response.rb:283:in read_body _0' from D:/Ruby24-x64/lib/ruby/2.4.0/net/http/response.rb:204:inread_body '
from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ultrahook-0.1.4/lib/ultrahoo k/client.rb:155:in block (2 levels) in init_stream' from D:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:1455:inblock in transpor t_request'
from D:/Ruby24-x64/lib/ruby/2.4.0/net/http/response.rb:165:in reading_b ody' from D:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:1454:intransport_request '
from D:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:1416:in request' from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ultrahook-0.1.4/lib/ultrahoo k/client.rb:153:inblock in init_stream'
from D:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:877:in start' from D:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:608:instart'
from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ultrahook-0.1.4/lib/ultrahoo k/client.rb:148:in init_stream' from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ultrahook-0.1.4/lib/ultrahoo k/client.rb:65:instart'
from D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ultrahook-0.1.4/bin/ultrahoo k:6:in <top (required)>' from D:/Ruby24-x64/bin/ultrahook:22:inload'
from D:/Ruby24-x64/bin/ultrahook:22:in `

'
There is any workaroud solution on ruby ?

Thank you

**Comment by rhenium** [comment]
As I wrote in https://github.com/ruby/openssl/issues/148#issuecomment-329965157, it's most likely a server issue.

**Comment by ioquatix** [comment]
If this is still a problem, please open a new issue with a full repro.
