### ISSUE TITLE
Appveyor - openssl version

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/openssl#157]
I suspect [appveyor.yml:17](https://github.com/ruby/openssl/blob/14e116554b56b722337b285adfc30481155dd1de/appveyor.yml#L17)
```
openssl version
```
is the version of OpenSSL contained in `C:\OpenSSL-Win32\`.  If that's the intent, then never mind.

Otherwise
```
ruby -rdevkit -e "puts `openssl version`"
```
Will show the version of OpenSSL that the compile/build will be using.

FYI - ruby trunk build is now built on Appveyor and stored as an artifact.

**Comment by rhenium** [comment]
https://ci.appveyor.com/project/ruby/openssl/build/job/tlb05qyww9g4hgk4

```
[00:00:02] ruby -v
[00:00:03] ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]
[00:00:03] openssl version
[00:00:03] OpenSSL 1.0.2j  26 Sep 2016
[...]
[00:03:06] C:/Ruby24-x64/bin/ruby.exe -I./lib -ropenssl -ve'puts OpenSSL::OPENSSL_VERSION, OpenSSL::OPENSSL_LIBRARY_VERSION'
[00:03:06] ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]
[00:03:06] OpenSSL 1.0.2k  26 Jan 2017
[00:03:06] OpenSSL 1.0.2k  26 Jan 2017
[00:03:06] Loaded suite C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_test_loader
```

Right, it's running a wrong openssl. It seems I accidentally added that in commit 26f928baa819cf06a3efd435a8ec28731d1da3f8. Since the test suite doesn't actually use the 'openssl' command line tool, the line should simply be removed.

**Comment by MSP-Greg** [comment]
> Since the test suite doesn't actually use the 'openssl' command line tool, the line should simply be removed.

In some respects, it does verify that you're using the package you think you are...

Do you think the command line tool should be included with ruby?  If so, maybe in the 'ruby_builtin_dlls' folder (rather than in 'bin', which would often be in user's path)?

Also, if you ever have need for info about ruby versions or MSYS2/MinGW packages on Appveyor, see <https://ci.appveyor.com/project/MSP-Greg/appveyor-ruby>.  It runs twice a day, shortly after my trunk build finishes...

**Comment by rhenium** [comment]
The 'test' Rake task prints OpenSSL::OPENSSL_VERSION and OpenSSL::OPENSSL_LIBRARY_VERSION. I think it's enough.

**Comment by MSP-Greg** [comment]
You're right.  Sorry for not noticing that...
