### ISSUE TITLE
HKDF support

### ISSUE THREAD

**Issue by bdewater** [ruby/openssl#172]
https://github.com/ruby/openssl/pull/109 added support for scrypt as a KDF. OpenSSL also [supports](https://github.com/openssl/openssl/blob/master/crypto/kdf/hkdf.c) HKDF ([RFC 5869](https://tools.ietf.org/html/rfc5869)).

According to https://github.com/openssl/openssl/pull/355 use cases include TLS 1.3 and QUIC, personally I've used it for [Android Pay](https://developers.google.com/android-pay/integration/payment-token-cryptography#decrypting-the-payment-token) token decryption. Could support be added?

**Comment by rhenium** [comment]
Seems like a nice feature to have.

**Comment by rhenium** [comment]
#173
