### ISSUE TITLE
SSL_CERT_FILE regression

### ISSUE THREAD

**Issue by HoneyryderChuck** [ruby/openssl#187]
I'm getting the following error in my test set-up with ruby 2.5.0:

```
>  OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (unable to get local issuer certificate)
...
```

This happens because the server certificate is self-generated. However, this certificate was signed by my custom CA, and the path to the CA has been set dynamically using the `SSL_CERT_FILE`. In fact, this very same test under the same conditions works in ruby 2.1 up to 2.4 , so I think that this was a regression.

Version: 2.1.0

**Comment by HoneyryderChuck** [comment]
I've tried running the same tests under latest ruby 2.4 and ruby openssl 2.1.0 and it works well... I have no idea why, I was expecting it not to work.

**Comment by rhenium** [comment]
The environment variable SSL_CERT_FILE is a feature of the OpenSSL library (not the binding). IIRC, the environment variable is not supported by LibreSSL.

**Comment by HoneyryderChuck** [comment]
I thought the same, but then how does it work for other rubies? Do you think it was an openssl regression then?

**Comment by rhenium** [comment]
I suspect you have both OpenSSL and LibreSSL in the system and your Ruby 2.5's openssl is linked against the LibreSSL. The constant OpenSSL::OPENSSL_LIBRARY_VERSION contains the version string provided by libcrypto.

**Comment by HoneyryderChuck** [comment]
@rhenium that explains it in my local environment, but I also happen to be using a ruby 2.5 docker image (alpine, in this case) where this also happens. I assume that this doesn't use LibreSSL, and even if it did, this should also happen with the ruby 2.4 alpine image, which it doesn't.

**Comment by ioquatix** [comment]
Please reopen this issue if you can provide a repro and/or failing spec/test PR.
