### ISSUE TITLE
How to build on travis

### ISSUE THREAD

**Issue by ioquatix** [ruby/openssl#188]
I am trying to use `ALPN` features of OpenSSL, which require v1.0.2 or v1.1.0 of OpenSSL.

Unfortunately trusty on travis only include v1.0.1

I see you have a docker image for running the tests, but I was wondering if there was a simpler way to do this.

- Is it possible to install more recent packages of `openssl` from `xenial`? Do we also need to install `libssl-dev`?
- Can we compile from source?

Do you think it makes sense to conditionally enable the `OpenSSL::SSL::SSLSocket#alpn_protocol` and related `SSLContext` methods? How is it determined? At compile time of the native extensions, or when loading the library?

I've honestly found this a bit tricky to get right. I also tried using `xenial` on travis but it was a bit unreliable.

Perhaps one option is to make an openssl gem which includes compiled library of more recent openssl library.

I'm open to ideas.

**Comment by ioquatix** [comment]
Okay so after a lot of mucking about, I finally figured out two workable approaches.

Both methods require an initial first step of installing openssl and libssl-dev from xenial.

The 2nd step differs:

1/ Ask rvm to rebuild from source

or

2/ Specify openssl as a gem dependency

The first approach, rebuilding ruby with rvm, is slow but works on all versions tested.

The second approach, only works with Ruby 2.3 and 2.4 - I can't seem to get Ruby 2.5 to use the recompiled version of openssl as a gem.

**Comment by ioquatix** [comment]
Here is the travis build: https://travis-ci.org/socketry/async-http/builds/343697522

Here is the travis config: https://github.com/socketry/async-http/blob/master/.travis.yml

Here is the gemspec: https://github.com/socketry/async-http/blob/master/async-http.gemspec#L23

I assume the gemspec is loaded via the gem file when travis runs the tests.

**Comment by nisanth074** [comment]
@ioquatix Why is it necessary to install the `openssl` package? Won't just `libssl-dev` suffice?

**Comment by ioquatix** [comment]
Because by default Ruby compiles against the current `libssl-dev` and doesn't version sniff the dynamic library. It's a fine approach, but it means that you need to recompile Ruby after updating `openssl` to get the new functionality (e.g. `alpn`).

**Comment by ioquatix** [comment]
This issue is largely irrelevant now.
