### ISSUE TITLE
ruby 2.5.1 OpenSSL::X509::Certificate.new fails with NameError

### ISSUE THREAD

**Issue by no-mercy** [ruby/openssl#200]
When i try to generate new certificate, it fails with OpenSSL::X509::NameError (X509_NAME_print_ex) error.

Environment: macOS 10.13.4, rbenv

Steps to reproduce:

require 'openssl'
OpenSSL::X509::Certificate.new

**Comment by no-mercy** [comment]
Update: it is ":inspect" method error on OpenSSL::X509::Certificate instance

**Comment by rhenium** [comment]
Minimal reproduce code:

```
$ ruby -ropenssl -e'p OpenSSL::X509::Name.new.to_s(OpenSSL::X509::Name::RFC2253)'
```

The handling of X509_NAME_print_ex() return value seems wrong.
