### ISSUE TITLE
Installing openssl with bundler

### ISSUE THREAD

**Issue by emilianodellacasa** [ruby/openssl#210]
I am trying to install openssl using bundle on appveyor. 

Due to appveyor limitations, I have to provide the path to openssl headers but I have not found to do it using bundler.

in the documentation it is clear that using gem you have to use the command

`gem install openssl -- --with-openssl-dir=/opt/openssl`

but what about bundler? What is the right way to do that?

**Comment by rhenium** [comment]
It's in [Bundler's FAQ](https://bundler.io/v1.16/guides/faq.html#i-have-a-c-extension-that-requires-special-flags-to-install), at section "I Have a C Extension That Requires Special Flags to Install".

**Comment by emilianodellacasa** [comment]
Thank you so much, but maybe it woiuld be better to include the specific command also on openssl README
