### ISSUE TITLE
Ruby 2.3 exhibiting odd behaviour?

### ISSUE THREAD

**Issue by ioquatix** [ruby/openssl#213]
We are trying to understand what is going on here:

https://github.com/socketry/falcon/issues/13

The SSL context is set up according to this logic:

https://github.com/socketry/localhost/blob/de8964b6fe639e6638089095ec802ac26a8e7b14/lib/localhost/authority.rb#L105-L114

You can see the output generated by `curl --verbose`:

https://github.com/socketry/falcon/issues/13#issuecomment-412134663

The only difference is running Ruby 2.3.6 vs 2.5.1, the former which doesn't seem to work but the latter which does.

So far, the only solution I'm seeing is to support Ruby 2.4 as a minimum since it appears 2.3 is broken?

**Comment by ioquatix** [comment]
Okay the bug was that calling `context.freeze` causes the context to fail in strange ways. The solution was to remove `context.freeze`. I think this is a bug, but there was a workable solution, and it's probably due to something wrong in older rubies that has already been fixed.

**Comment by rhenium** [comment]
Seems this is a duplicate of #85. The bug was fixed by v2.0.0 (bundled in Ruby 2.4).

**Comment by ioquatix** [comment]
Thanks for following up. I clearly see the problem now and am glad it is solved.
