### ISSUE TITLE
SSLContext.dup is broken

### ISSUE THREAD

**Issue by ioquatix** [ruby/openssl#218]
```
^_^ > pry     
[1] pry(main)> require 'openssl'
=> true
[2] pry(main)> OpenSSL::SSL::SSLContext.new.dup
NoMethodError: undefined method `initialize_copy' for #<OpenSSL::SSL::SSLContext:0x00007ffc4e37c330>
from (pry):2:in `initialize_dup'

^_^ > gem list | grep openssl
openssl (default: 2.1.0)
^_^ > ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
```

**Comment by ioquatix** [comment]
Before I was calling freeze but it broken on 2.3, so I tried calling super, it broken on 2.4

**Comment by rhenium** [comment]
SSLContext is thread-safe once you call SSLContext#setup (also automatically called through the first SSLSocket#{accept,connect}).

**Comment by ioquatix** [comment]
Yes but once you call accept from a thread it’s no longer synchronised in any way so that’s bad. Is `#setup` available on >= 2.3?

**Comment by rhenium** [comment]
Yes, SSLContext#setup is available in previous versions as well.

**Comment by ioquatix** [comment]
Thanks for your help and knowledge.

**Comment by ioquatix** [comment]
If it doesn't work, why not use `undef` to remove `#dup`?
