### ISSUE TITLE
Add support for using PSS padding for RSA private_encrypt/public_decrypt

### ISSUE THREAD

**Issue by JamieCoder1** [ruby/openssl#219]
I'm not able to use `RSA_PKCS1_PSS_PADDING` for `rsa.private_encrypt` or `rsa.public_decrypt`. The constant `OpenSSL::PKey::RSA::PKCS1_PSS_PADDING` isn't even defined.

Is there a reason for this? I thought [`PKCS1_PSS` was preferred over `PKCS1`](https://commondatastorage.googleapis.com/chromium-boringssl-docs/rsa.h.html#RSA_private_encrypt)? From that link it seems like `PKCS1_PSS` should be supported for `private_encrypt`/`public_decrypt`:

> It returns the number of bytes written, or `-1` on error. The padding argument must be one of the `RSA_*_PADDING` values. If in doubt, `RSA_PKCS1_PADDING` is the most common but `RSA_PKCS1_PSS_PADDING` (via the `EVP_PKEY` interface) is preferred for new protocols.

Would expect to be able to do:

```ruby
require 'openssl'

padding = OpenSSL::PKey::RSA::PKCS1_PSS_PADDING
priv = OpenSSL::PKey::RSA.new 2048
pub = priv.public_key

data = 'x' * (2048/8 - 11)
enc = priv.private_encrypt data, padding
dec = pub.public_decrypt enc, padding

puts dec == data
```

Using Ruby 2.3 and OpenSSL 1.0.2, but have also tried with OpenSSL 1.1.1-pre8.

Sorry if I'm missing something obvious…

**Comment by JamieCoder1** [comment]
Following up here…

To be able to do this, this gem would need to utilize [RSA EMSR-PSS](https://pdfs.semanticscholar.org/b459/5fffe0562776a2830c7b525ba9f641110d7a.pdf) (sec. 1.3), which allows message recovery (since encrypting with a private key is signing, not encryption, as the name would suggest.)

I think that would be a great addition to this lib for a more secure private encrypt scheme.

**Comment by bdewater** [comment]
I think you're looking for `OpenSSL::PKey::RSA#sign_pss` and `#verify_pss`?

**Comment by rhenium** [comment]
Yes, `OpenSSL::PKey::RSA#sign_pss` is the method (version 2.1.0; 2017-12).
