### ISSUE TITLE
Could not find a valid gem 'openssl'

### ISSUE THREAD

**Issue by maximnik** [ruby/openssl#24]
Hi

Tried to use gem 'openssl' in Gemfile., but got error:

ERROR:  Could not find a valid gem 'openssl' (>= 0) in any repository

Checked on rubygems.org and there is no openssl gem. There are many others, but not this specific.

Is this known issue? Was openssl officially deprecated?

Thanks.

**Comment by jasongfr** [comment]
I'm getting the same error too when deploying to AWS Elasticbeanstalk and bundler is run:

Could not find openssl-1.0.0.beta in any of the sources.

**Comment by zzak** [comment]
This is because the gem has not been released outside of Ruby, it's still included as a default gem when you install Ruby and hasn't been pushed to rubygems.org yet.

Please wait a little longer~
