### ISSUE TITLE
Error while installing gem openssl on Windows

### ISSUE THREAD

**Issue by ividovic** [ruby/openssl#240]
I am trying to install openssl gem on Windows but I am getting following error:
```
ERROR:  Error installing openssl:
    ERROR: Failed to build gem native extension.

current directory: 

C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/openssl-2.1.2/ext/openssl
C:/RailsInstaller/Ruby2.3.3/bin/ruby.exe -r ./siteconf20190130-612-n5x9sx.rb extconf.rb --with-openssl-dir=C:\Program Files\OpenSSL-Win64\lib
checking for t_open() in -lnsl... no
checking for socket() in -lsocket... no
checking for main() in -lws2_32... yes
checking for main() in -lgdi32... yes
checking for main() in -lcrypt32... yes
checking for openssl/ssl.h... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
```
I have tried different approaches and setting but without success. I have installed openssl library and when I type
`openssl version`

in CMD, I get

`OpenSSL 1.1.1a  20 Nov 2018`

My ruby version is

`ruby 2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]`

My rails version is

`Rails 5.1.6`

I appreciate any help and suggestion.

**Comment by LuminousPath** [comment]
if you know where you installed openssl, you can use the command `gem install openssl -- --with-openssl-dir=<path_to_openssl_installation>` and it should fix that error

**Comment by rhenium** [comment]
> checking for openssl/ssl.h... no

This means ruby-openssl failed to find the OpenSSL library's header files which are necessary to build the extension.

> C:/RailsInstaller/Ruby2.3.3/bin/ruby.exe -r ./siteconf20190130-612-n5x9sx.rb extconf.rb --with-openssl-dir=C:\Program Files\OpenSSL-Win64\lib

Most likely the path `C:\Program Files\OpenSSL-Win64\lib` was wrong.
