### ISSUE TITLE
Misleading documentation for renegotiation callback

### ISSUE THREAD

**Issue by p-mongo** [ruby/openssl#256]
https://ruby-doc.org/stdlib-2.6.1/libdoc/openssl/rdoc/OpenSSL/SSL/SSLContext.html#attribute-i-renegotiation_cb-label-Disable+client+renegotiation states for renegotiation_cb:

> A callback invoked whenever a new handshake is initiated. May be used to disable renegotiation entirely.

The docstring appears to imply that the callback is called for the initial connection, however this is not the case in MRI - as the *name* but not the description above suggests, the callback is NOT called for the initial connection.

JRuby seems to have implemented the callback according to the quoted description and does call it for the initial connection, leading to the provided sample code to disable renegotiation breaking connectivity entirely in jruby, for which I filed https://github.com/jruby/jruby-openssl/issues/180.

Based on the attribute name and actual behavior, I believe the description should be changed to state that the callback is invoked for connection attempts other than the initial one.

**Comment by ioquatix** [comment]
@headius can you check what's going on here?

@p-mongo can you make a PR to fix the documentation?

**Comment by p-mongo** [comment]
I will work on a PR.

**Comment by ioquatix** [comment]
Any update?

**Comment by p-mongo** [comment]
Proposed PR: https://github.com/ruby/openssl/pull/296

**Comment by ioquatix** [comment]
@headius the documentation has been updated to match the implementation more clearly, which definitely puts JRuby out of sync. Feel free to open a new issue if you feel the solution as merged is incorrect.
