### ISSUE TITLE
[Documentation] Upgrade hints?

### ISSUE THREAD

**Issue by rubyFeedback** [ruby/openssl#274]
Hello ruby-maintainers of openssl,

To me openssl is quite important because rubygems requires openssl, and I need openssl to publish new gems for example.

Would it be possible to add a subsection to the main README, that could collect some advice in regards to upgrading? E. g. when it is safe to upgrade and when it is not. Openssl itself changes quite frequently and I am not so sure which versions work fine; and perhaps other users may also appreciate any help they could get here in regards to the question "Is it ok to upgrade?", in particular when it comes to code that may no longer work. I understand that this is not necessarily solely confined to the openssl-bindings here, since "external" code, such as the one in rubygems for openssl, may also be different or require changes, and so forth; but I am asking here mostly from a user perspective here, not necessarily a developer perspective, so I would appreciate a subsection that may be named "UPGRADE" or something like that. Thanks for considering! (It is admittedly a low priority issue.)

**Comment by ioquatix** [comment]
I believe that it should be fair enough to assume that semantic versioning applies, at least in the case of releases of this gem.

**Comment by nurse** [comment]
Thank you for feedback.
I understand your concern about compatibility of fundamental gems.
As a user I also share the concern.

As far as I know and I expect openssl.gem won't introduce such incompatibility.
And if it needs such large incompatibility maybe because of openssl library, it will have such document.
