### ISSUE TITLE
OpenSSL::SSL::SSLServer#listen default argument value

### ISSUE THREAD

**Issue by thekuwayama** [ruby/openssl#286]
`OpenSSL::SSL::SSLServer#listen` default argument `backlog` is [5](https://github.com/ruby/openssl/blob/88745f6d66cb8125ab2a7851b925120a57a00ca5/lib/openssl/ssl.rb#L505).
It is sometimes less than TCPServer#listen default argument `Socket::SOMAXCONN`.

For example, on macOS `Socket::SOMAXCONN` is defined at `sys/socket.h` and its value is 128.

I think that there are solutions like below

- use `Socket::SOMAXCONN` (but neet to require `socket`)
- define constant that is related to SOMAXCONN

**Comment by ioquatix** [comment]
I think require socket is okay.

**Comment by thekuwayama** [comment]
@ioquatix Thank you for comments. :smile:
I send a PR!
