### ISSUE TITLE
How can I get the IP address of an already closed connection that caused an error?

### ISSUE THREAD

**Issue by log69** [ruby/openssl#290]
Dear developers, I have the following Ruby code on server running MRI Ruby 2.5.1:

    #!/usr/bin/env ruby
    require "socket"
    require "openssl"
    cert_path = Dir["/etc/letsencrypt/live/example.com/fullchain.pem"].first
    key_path = Dir["/etc/letsencrypt/live/example.com/privkey.pem"].first
    chain_path = Dir["/etc/letsencrypt/live/example.com/chain.pem"].first
    context = OpenSSL::SSL::SSLContext.new
    context.cert = OpenSSL::X509::Certificate.new( File.read( cert_path ))
    context.key = OpenSSL::PKey::RSA.new( File.read( key_path ))
    context.extra_chain_cert = [ OpenSSL::X509::Certificate.new( File.read( chain_path )) ]
    port = 4444
    t = TCPServer.new( port )
    s = OpenSSL::SSL::SSLServer.new( t, context )
    begin
    r = s.accept
    rescue
    # get client ip here
    p r.methods.sort
    end

I can connect to the server just fine with this command:

    curl https://example.com:4444

If I cause an error on purpose like this (notice to have http instead of https):

    curl http://example.com:4444

Then I cannot seem to get the IP address of the client from anywhere because the connection has already closed. I'm getting attacks with many requests like this and I'd like to firewall these IP addresses, only I would need the addresses to do so. Any idea how to get the IP address of the remote client that caused the error? Catching the exception and printing the error object contains no useful info. Thank you.

**Comment by ioquatix** [comment]
You will need to implement the connection handling yourself.

Something like:

https://github.com/socketry/async-io/blob/582b40434859efd1abd6a2519cb07d144b500bed/lib/async/io/ssl_socket.rb#L131-L150

**Comment by ioquatix** [comment]
If you think the exception should have the client address, please feel free to submit a PR, or create a new issue to that effect "Server #accept exception does not contain useful information". Please include what it currently looks like and what you think would be better.

**Comment by log69** [comment]
@ioquatix Thank you.
