### ISSUE TITLE
Server #accept exception does not contain useful information

### ISSUE THREAD

**Issue by log69** [ruby/openssl#291]
When connecting to the SSL layer and an error occurs, the connection closes and the IP of the remote client cannot be determined through the exception process. Since it is essential for every service to be able to handle remote attacks and provide stability, I believe it would be useful to provide the IP address in the exception procedure so the IP can be firewalled or debugged or handled in any way. Otherwise it would be very easy to do an attack to an SSL socket by connecting to it with different or wrongly prepared protocols.

#peeraddr is available if the connection builds up successfully. It would be nice to have this in the exception process as well, as the peer address of the client having caused the exception.

Example code is here: https://github.com/ruby/openssl/issues/290#issue-520590803

Everything else is nice and works well. Thank you.

**Comment by ioquatix** [comment]
@vinistock this could be a good first issue to work on. I have a few others in mind, but if you can take a stab at this one we can go from there.
