### ISSUE TITLE
Export RSA private key to PKCS8 format

### ISSUE THREAD

**Issue by akostadinov** [ruby/openssl#294]
Hi, I don't see any way to export RSA private key to PKCS8 PEM format as for example required by Chrome extension `.crx`.

There is a discontinued rubygem about this [1] but I think a `to_pkcs8` method would nicely fit into the main library. There is a pull request for making it work with recent ruby.

[1] https://github.com/postageapp/openssl_pkcs8
[2] https://github.com/postageapp/openssl_pkcs8/pull/4/files

**Comment by ioquatix** [comment]
Great, can you make a PR here?

**Comment by akostadinov** [comment]
I don't expect to have time for this. I found I have another way around for the task at hand.

**Comment by ioquatix** [comment]
What is the other way?

**Comment by bdewater** [comment]
https://github.com/ruby/openssl/pull/119 covers this among other things. Perhaps the relevant commit(s) could be cherry-picked out of the larger work in there to support x25519.
