### ISSUE TITLE
Lookup ciphers programatically.

### ISSUE THREAD

**Issue by ioquatix** [ruby/openssl#304]
My advice would be to avoid specific support for any *particular*
digest algorithm.  Instead, provide bindings to:

  - `EVP_get_digestbyname()`,
  - `EVP_MD_CTX_create(3)`,
  - `EVP_DigestInit_ex(3)`,
  - `EVP_DigestUpdate(3)`,
  - `EVP_DigestFinal_ex(3)`,
  - `EVP_MD_CTX_destroy(3)`

which can they use *any* available digest algorithm (by name).

**Comment by rhenium** [comment]
> * `EVP_get_digestbyname()`,

This is what OpenSSL::Digest.new("digest-algo-name") currently does.

I agree with this idea in general. It's hard to maintain those constants for specific algorithms (as in lib/openssl/digest.rb) up to date, and I also think we should be agnostic on the algorithms.

The same goes for OpenSSL::Cipher.

**Comment by bdewater** [comment]
I think this can be closed now https://github.com/ruby/openssl/pull/362 is merged?

**Comment by ioquatix** [comment]
Yes
