### ISSUE TITLE
re-examination about `SSLContext#add_certificate_chain_file`

### ISSUE THREAD

**Issue by thekuwayama** [ruby/openssl#305]
`SSLContext#add_certificate_chain_file()` is able to load a chain certificates file. I want to re-examine this API.

As [commented](https://github.com/ruby/openssl/blob/62287bede47e34561279901758ff5a8195cc8a9d/ext/openssl/ossl_ssl.c#L2537L2542), the old setters(`SSLContext#cert=`, `key=`, `extra_chain_cert=`) are deprecated.
If `add_certificate_chain_file` is used, it is needed to call `key=` to load the private key associated with certificates.
That is, as provided `add_certificate_chain_file` and then it would be required `key=`.

The API that parses a chain certificates file is so nice and I think that is needed. So, I suggest 2 plans.

1. modify `add_certificate_chain_file` to accept the path to the private key. Also, it is needed to rename too.
2. provide `Certificate.load_file` and deprecate `add_certificate_chain_file`.

**Comment by ioquatix** [comment]
I agree.

Was `add_certificate_chain_file` actually released in any version?

**Comment by thekuwayama** [comment]
`add_certificate_chain_file` has not released yet. It is scheduled that is released in 2.2.0 version.

https://github.com/ruby/openssl/blob/62287bede47e34561279901758ff5a8195cc8a9d/History.md#L33

**Comment by ioquatix** [comment]
So we could  consider remove it before it’s released if we can implement the alternatives in time... do you have time to make PR?

**Comment by thekuwayama** [comment]
So sorry... I could not make the PR by the next release.

**Comment by ioquatix** [comment]
Don't be sorry, I'll see if I can take a stab. @hsbt if we decide to change this, what is the latest time we can merge this into Ruby 2.7?

**Comment by thekuwayama** [comment]
@ioquatix I sent PR(plan 1)!! 😃
> 1. modify `add_certificate_chain_file` to accept the path to the private key. Also, it is needed to rename too.
