### ISSUE TITLE
Awful message for wrong password

### ISSUE THREAD

**Issue by magikid** [ruby/openssl#33]
If a user types an incorrect password for their certificate, the error message they're give says "Neither PUB key nor PRIV key" which doesn't mean anything to most people. 

What else can trigger this error message and can it be updated to better reflect the ultimate cause of the issue?

**Comment by zzak** [comment]
Doing a quick search of the source shows us that this error message was implemented in the gem, so we can change it:

```
git grep 'PUB key nor PRIV key'
ext/openssl/ossl_pkey_dsa.c:248:            ossl_raise(eDSAError, "Neither PUB key nor PRIV key");
ext/openssl/ossl_pkey_rsa.c:247:            ossl_raise(eRSAError, "Neither PUB key nor PRIV key");
```

**Comment by rhenium** [comment]
Raising more accurate exception is not impossible - if OpenSSL's error queue contains PEM_R_BAD_DECRYPT, then the passphrase must be wrong.

~~~diff
diff --git a/ext/openssl/ossl_pkey_rsa.c b/ext/openssl/ossl_pkey_rsa.c
index f1b4f04..218f8f5 100644
--- a/ext/openssl/ossl_pkey_rsa.c
+++ b/ext/openssl/ossl_pkey_rsa.c
@@ -239,6 +239,13 @@ ossl_rsa_initialize(int argc, VALUE *argv, VALUE self)
 	in = ossl_obj2bio(arg);
 	rsa = PEM_read_bio_RSAPrivateKey(in, NULL, ossl_pem_passwd_cb, (void *)pass);
 	if (!rsa) {
+	    long e;
+	    while ((e = ERR_get_error())) {
+		if (ERR_GET_REASON(e) == PEM_R_BAD_DECRYPT) {
+		    BIO_free(in);
+		    ossl_raise(eRSAError, "passphrase invalid");
+		}
+	    }
 	    OSSL_BIO_reset(in);
 	    rsa = PEM_read_bio_RSA_PUBKEY(in, NULL, NULL, NULL);
 	}
~~~

But I don't know if I can rely on the 'error reason'. Is it stable enough?

**Comment by rhenium** [comment]
I'm closing this for now. Unfortunately, I can't come up with a better and simple way to achieve this.
