### ISSUE TITLE
test_add_certificate_chain_file fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by mame** [ruby/openssl#334]
https://rubyci.org/logs/rubyci.s3.amazonaws.com/ubuntu/ruby-master/log/20200216T093010Z.fail.html.gz

```
  1) Failure:
OpenSSL::TestSSL#test_add_certificate_chain_file [/data/chkbuild/tmp/build/20200216T093010Z/ruby/test/openssl/test_ssl.rb:190]:
Failed assertion, no message given.

  2) Failure:
OpenSSL::TestSSL#test_add_certificate_chain_file [/data/chkbuild/tmp/build/20200216T093010Z/ruby/test/openssl/utils.rb:166]:
<[]> expected but was
<["error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small"]>.
```

I think `test/openssl/fixtures/chain/server.crt` is too short for the default settings of newer OpenSSL (maybe 1.1.1d or later). The files are added at https://github.com/ruby/openssl/commit/10afb354f771c2cf67e21de2127772e32124bb47, but it is not documented how to create the files.

To suppress the failures on ruby/ruby CI, tentatively I added a skip for the test: https://github.com/ruby/ruby/commit/e37e0bfa989bccf219e82ad7a73d415a8b7add80

**Comment by rhenium** [comment]
Some patches for that newly added feature have been temporarily reverted due to #318, which included a complete rewrite of the test case in a way the static file will not be used.

It will be restored before tagging 2.2.0.

**Comment by rhenium** [comment]
This is resolved now.
