### ISSUE TITLE
OpenSSL::TestSSL#test_fallback_scsv fails

### ISSUE THREAD

**Issue by mame** [ruby/openssl#336]
https://rubyci.org/logs/rubyci.s3.amazonaws.com/ubuntu/ruby-master/log/20200216T123005Z.fail.html.gz
```
  1) Failure:
OpenSSL::TestSSL#test_fallback_scsv [/data/chkbuild/tmp/build/20200216T123005Z/ruby/test/openssl/utils.rb:299]:
exceptions on 1 threads:
SSL_connect returned=1 errno=0 state=error: no protocols available
```

It seems to occur on only ubuntu 20.04.

**Comment by mame** [comment]
Tentatively skipped on  https://github.com/ruby/ruby/commit/3fbcdac3e40f68667a9a1b5a2efed215762260c0

**Comment by MSP-Greg** [comment]
@mame

All of the platforms tested here (Ubuntu, macOS, & Windows) are testing against OpenSSL 1.1.1d at a minimum of Ruby 2.5 thru head/master.

Can the pends/skips be platform specific so we don't lose the testing where it does pass?

**Comment by mame** [comment]
Note that the skip is only on ruby/ruby.  If you give me a condition, I can use it.  But we should make effort to fix the issue than to seek a better skip condition.

**Comment by rhenium** [comment]
In http://changelogs.ubuntu.com/changelogs/pool/main/o/openssl/openssl_1.1.1d-2ubuntu3/changelog:

>   * Set OPENSSL_TLS_SECURITY_LEVEL=2 as compiled-in minimum security
>     level. Change meaning of SECURITY_LEVEL=2 to prohibit TLS versions
>     below 1.2 and update documentation. Previous default of 1, can be set
>     by calling SSL_CTX_set_security_level(), SSL_set_security_level() or
>     using ':@SECLEVEL=1' CipherString value in openssl.cfg.

So it seems Ubuntu 20.04 will have TLS 1.2 and TLS 1.3 only. Since the fallback SCSV is a mechanism to prevent downgrade attack on TLS 1.2 or older, the test case should be just skipped in that case.

**Comment by mame** [comment]
Thank you very much!!

**Comment by MSP-Greg** [comment]
An interesting document is at:
https://github.com/openssl/openssl/blob/master/doc/man3/SSL_CTX_set_security_level.pod

The issue of particular OpenSSL builds having more strict security restrictions has come up before, and I never found the mechanism for doing so.

We could create custom Ruby/OpenSSL builds with settings of 2 and/or 3 to run CI against.  I could do that with mingw or mswin...

**Comment by MSP-Greg** [comment]
Or, the test framework could be modified to add a global 'security_level' setting and tests could be run against higher levels than the default of 1.
