### ISSUE TITLE
OpenSSL::SSL::SSLContext#security_level, setting in tests

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/openssl#341]
Did  a quick patch to allow a global test method (`#context_new`) that replaces all the `OpenSSL::SSL::SSLContext.new` calls.  It allows setting `OpenSSL::SSL::SSLContext#security_level`, based on an ENV variable.  When the ENV variable is not set, tests are identical to current.

This may be helpful for testing when issues arise from CI at https://rubyci.org/ where OpenSSL is compiled with higher security level?

Below are the results.

<details>
  <summary>Security level 2<br/>
473 tests, 4259 assertions, 2 failures, 0 errors, 1 pendings
</summary>
<pre><code>1)   187:
     188:   def test_add_certificate_chain_file
     189:     ctx = context_new
  =&gt; 190:     assert ctx.add_certificate_chain_file(Fixtures.file_path("chain", "server.crt"))
     191:   end
     192:
     193:   def test_sysread_and_syswrite
test/openssl/test_ssl.rb:190:in `test_add_certificate_chain_file'
Failure: test_add_certificate_chain_file(OpenSSL::TestSSL): &lt;false&gt; is not true.

<br/>
2) test/openssl/utils.rb:181:in `teardown'
&lt;[]&gt; expected but was
&lt;["error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small"]&gt;
</code></pre>
</details>

<details>
<summary>Security level 3<br/>
473 tests, 4222 assertions, 4 failures, 1 errors, 1 pendings
</summary>
<pre><code>1)   187:
     188:   def test_add_certificate_chain_file
     189:     ctx = context_new
  =&gt; 190:     assert ctx.add_certificate_chain_file(Fixtures.file_path("chain", "server.crt"))
     191:   end
     192:
     193:   def test_sysread_and_syswrite
test/openssl/test_ssl.rb:190:in `test_add_certificate_chain_file'
Failure: test_add_certificate_chain_file(OpenSSL::TestSSL): &lt;false&gt; is not true.

<br/>
2) test/openssl/utils.rb:181:in `teardown'
&lt;[]&gt; expected but was
&lt;["error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small"]&gt;

<br/>
3) test/openssl/test_ssl.rb:167:in `test_add_certificate_multiple_certs'
test/openssl/utils.rb:227:in `start_server'
test/openssl/utils.rb:227:in `pipe'
test/openssl/utils.rb:237:in `block in start_server'
test/openssl/test_ssl.rb:163:in `block in test_add_certificate_multiple_certs'
test/openssl/envutil.rb:109:in `suppress_warning'
     161:       ctx.ecdh_curves = "P-256" unless openssl?(1, 0, 2)
     162:       ctx.add_certificate(@svr_cert, @svr_key, [@ca_cert]) # RSA
     163:       EnvUtil.suppress_warning do # !add0_chain_supported
  =&gt; 164:         ctx.add_certificate(ecdsa_cert, ecdsa_key, [ca2_cert])
     165:       end
     166:     }
     167:     start_server(ctx_proc: ctx_proc) do |port|
test/openssl/test_ssl.rb:164:in `block (2 levels) in test_add_certificate_multiple_certs'
test/openssl/test_ssl.rb:164:in `add_certificate'
Error: test_add_certificate_multiple_certs(OpenSSL::TestSSL):
OpenSSL::SSL::SSLError: SSL_CTX_set0_chain: ca key too small

<br/>
4)   1510:       ctx.ciphers = "DH:!NULL" # use DH
     1511:       ctx.tmp_dh_callback = nil
     1512:     }
  =&gt; 1513:     start_server(ctx_proc: ctx_proc) do |port|
     1514:       EnvUtil.suppress_warning { # uses default callback
     1515:         assert_nothing_raised {
     1516:           server_connect(port) { }
test/openssl/test_ssl.rb:1513:in `test_connect_works_when_setting_dh_callback_to_nil'
test/openssl/utils.rb:227:in `start_server'
test/openssl/utils.rb:227:in `pipe'
test/openssl/utils.rb:314:in `block in start_server'
test/openssl/envutil.rb:281:in `assert_join_threads'
Failure: test_connect_works_when_setting_dh_callback_to_nil(OpenSSL::TestSSL):
  exceptions on 1 threads:
  #&lt;Thread:0x00000000068c6e90 test/openssl/utils.rb:285 dead&gt;:
  lib/openssl/ssl.rb:524:in `accept': SSL_accept returned=1 errno=0 state=error: dh key too small (OpenSSL::SSL::SSLError)
        from lib/openssl/ssl.rb:524:in `accept'
        from test/openssl/utils.rb:258:in `block (3 levels) in start_server'
        from test/openssl/utils.rb:254:in `loop'
        from test/openssl/utils.rb:254:in `block (2 levels) in start_server'

<br/>
5)   1376:         ctx.ssl_version = :TLSv1_2
     1377:         ctx.ciphers = "kRSA"
     1378:       }
  =&gt; 1379:       start_server(ctx_proc: ctx_proc1) do |port|
     1380:         ctx = context_new
     1381:         ctx.ssl_version = :TLSv1_2
     1382:         ctx.ciphers = "kRSA"
test/openssl/test_ssl.rb:1379:in `test_get_ephemeral_key'
test/openssl/utils.rb:227:in `start_server'
test/openssl/utils.rb:227:in `pipe'
test/openssl/utils.rb:314:in `block in start_server'
test/openssl/envutil.rb:281:in `assert_join_threads'
Failure: test_get_ephemeral_key(OpenSSL::TestSSL):
  exceptions on 1 threads:
  #&lt;Thread:0x00000000079f7368 test/openssl/utils.rb:285 dead&gt;:
  test/openssl/test_ssl.rb:1678:in `connect': SSL_connect returned=1 errno=0 state=error: no ciphers available (OpenSSL::SSL::SSLError)
        from test/openssl/test_ssl.rb:1678:in `server_connect'
        from test/openssl/test_ssl.rb:1383:in `block in test_get_ephemeral_key'
        from test/openssl/utils.rb:291:in `block (2 levels) in start_server'
</code></pre>
</details>

**Comment by rhenium** [comment]
Thanks for the work. While it's unrealistic that distros start using security level = 3 anytime soon and I don't think we need the test cases to always pass with higher security levels, this revealed some issues that should be resolved.

> ```
> 1)
> Failure: test_add_certificate_chain_file(OpenSSL::TestSSL): <false> is not true.
> 2) test/openssl/utils.rb:181:in `teardown'
> <["error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small"]>
> ```

Pending changes in https://github.com/ruby/openssl/issues/318.

> ```
> 3) test/openssl/test_ssl.rb:167:in `test_add_certificate_multiple_certs'
> ```

RSA key shorter than 3072 bits is rejected. The test case should be using rsa-{1,2,3}.pem instead since the size doesn't matter here.

> ```
> 4)   1510:       ctx.ciphers = "DH:!NULL" # use DH
> Failure: test_connect_works_when_setting_dh_callback_to_nil(OpenSSL::TestSSL):
> ```

The default DH parameters are rejected. It's 4 years ago we generated in https://github.com/ruby/openssl/pull/45, but the size is still considered fine.

[I personally don't like having the default parameters in this library. IMO it should be removed if we could ignore compatibility.]

> ```
> 5)   1376:         ctx.ssl_version = :TLSv1_2
> Failure: test_get_ephemeral_key(OpenSSL::TestSSL):
> ```

Non-forward-secrecy cipher suite is rejected. The test case should use `pend`.

**Comment by rhenium** [comment]
`1)` and `2)` (the same issue) are tracked by https://github.com/ruby/openssl/issues/334.
`3)` is fixed by https://github.com/ruby/openssl/commit/4dd580ce2dbfdcca66ac6e8279ca32cff9af3183.
`4)`, I'll leave it as is for now.
`5)` is fixed by https://github.com/ruby/openssl/commit/3a68ea4519235bbf1a5b1583b6c447c4d8ed02cf.

**Comment by MSP-Greg** [comment]
@rhenium

> While it's unrealistic that distros start using security level = 3 anytime soon

Once I was set up to set `ctx.security_level=`, generating test results for '3' was QED.  Although rather forward looking, the data might be helpful.

Thanks for the quick fixes.  Hopefully the OpenSSL tests at https://rubyci.org/ will be stable for a while...
