### ISSUE TITLE
Test failures with RHEL8 

### ISSUE THREAD

**Issue by hsbt** [ruby/openssl#353]
The openssl tests were failed on ruby repo. see https://rubyci.org/logs/rubyci.s3.amazonaws.com/rhel8/ruby-master/log/20200309T033003Z.fail.html.gz

@rhenium If you want to investigate it, I can create your account with its VM.

**Comment by rhenium** [comment]
The failures are caused by https://github.com/ruby/openssl/pull/216 and https://github.com/ruby/openssl/issues/334.

I will merge the needed fixes to ruby/ruby.

**Comment by rhenium** [comment]
The latest test run passed on RHEL8 now. Thanks for letting me know!
