### ISSUE TITLE
OpenSSL::PKCS7::read_smime for Italian e-bill

### ISSUE THREAD

**Issue by MatteoBortolotti** [ruby/openssl#365]
I am trying to implement a decoder for a bunch of files (e-bills with extension .xml.p7m) in my rails application with openssl gem.

My goal is to upload the encripted files and read them populating the database meanwhile. I don't need to verify the signature because i want to conserve the original file, with signature, as an attachment. The result should be the plain .xml for each file.

I can do this easily in the terminal with the following command:
`openssl smime -verify -noverify -in file.xml.p7m -inform DER -out file.xml`

I've tryied to follow the sample proposed at https://github.com/ruby/openssl/blob/master/sample/smime_read.rb doing something like this:
`OpenSSL::PKCS7::read_smime(File.read(file.xml.p7m))`
but i recive error:
`OpenSSL::PKCS7::PKCS7Error (no content type)`

I've also tried to encode the file in base64 but nothing changes.

I can't understand this error and i can't find a clear explanation of what else read_smime shuld expect as input. 

Thanks in advance.

**Comment by rhenium** [comment]
> `openssl smime -verify -noverify -in file.xml.p7m -inform DER -out file.xml`

Judging from this command line, the .p7m file is DER-encoded.

However, OpenSSL::PKCS7.read_smime expects a whole message in S/MIME format. To open a DER- or PEM-encoded file, use `OpenSSL::PKCS7.new(string)` instead.

**Comment by MatteoBortolotti** [comment]
I'm not sure about what's going on here. Sorry but it is my first time with encryption.

What i get with `OpenSSL::PKCS7.new(string)` is a pkcs7 object (well) and i can verify it and export certificates (very well). Seems good but i cannot export the file itself which is what i need.

Something that i think could be usefull:
`p7 = OpenSSL::PKCS7.new(string)`
` => #<OpenSSL::PKCS7:0x000055dd90585958 @data=nil, @error_string=nil>`

`p7.data`
` => nil`

`p7.recipients`
` => []`

`p7.to_s`
` => "-----BEGIN PKCS7-----\n     .......     -----END PKCS7-----\n"`

Sorry again, i'm trying to figure it out.

**Comment by rhenium** [comment]
OpenSSL::PKCS7#verify corresponds to PKCS7_verify(), which `openssl smime -verify` would internally use. On a successful verification (which is skipped by the OpenSSL::PKCS7::NOVERIFY flag), it stores the content in the `data` attribute.

```ruby
p7 = OpenSSL::PKCS7.new(...)
certs = nil
store = OpenSSL::X509::Store.new
indata = nil
flags = OpenSSL::PKCS7::NOVERIFY # openssl smime -verify -noverify
p7.verify(certs, store, indata, flags)
p p7.data
```

Note that I'm assuming here that the .p7m file contains a basic SignedData structure in it. PKCS#7 might have a very complex structure and I can't say for sure without looking at the file.

**Comment by MatteoBortolotti** [comment]
That work like a charm. Thanks a lot!
