### ISSUE TITLE
/root/ruby-2.7.1/.ext/x86_64-linux/openssl.so: symbol EC_GROUP_new_curve_GF2m, version OPENSSL_1_1_0 not defined in file libcrypto.so.1.1

### ISSUE THREAD

**Issue by tea1111980** [ruby/openssl#368]
======= logs:

in make install following:

making encs
make[1]: 进入目录“/root/ruby-2.7.1”
make[1]: 对“encs”无需做任何事。
make[1]: 离开目录“/root/ruby-2.7.1”
./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems -r./x86_64-linux-fake ./tool/rbinstall.rb --make="make" --dest-dir="" --extout=".ext" --mflags="" --make-flags="" --data-mode=0644 --prog-mode=0755 --installed-list .installed.list --mantype="doc" --exclude=doc
Traceback (most recent call last):
        15: from ./tool/rbinstall.rb:649:in `<main>'
        14: from ./tool/rbinstall.rb:713:in `<module:RbInstall>'
        13: from /root/ruby-2.7.1/lib/rubygems/core_ext/kernel_require.rb:92:in `require'
        12: from /root/ruby-2.7.1/lib/rubygems/core_ext/kernel_require.rb:92:in `require'
        11: from /root/ruby-2.7.1/lib/rubygems/installer.rb:11:in `<top (required)>'
        10: from /root/ruby-2.7.1/lib/rubygems/core_ext/kernel_require.rb:92:in `require'
         9: from /root/ruby-2.7.1/lib/rubygems/core_ext/kernel_require.rb:92:in `require'
         8: from /root/ruby-2.7.1/lib/rubygems/package.rb:44:in `<top (required)>'
         7: from /root/ruby-2.7.1/lib/rubygems/core_ext/kernel_require.rb:92:in `require'
         6: from /root/ruby-2.7.1/lib/rubygems/core_ext/kernel_require.rb:92:in `require'
         5: from /root/ruby-2.7.1/lib/rubygems/security.rb:12:in `<top (required)>'
         4: from /root/ruby-2.7.1/lib/rubygems/core_ext/kernel_require.rb:92:in `require'
         3: from /root/ruby-2.7.1/lib/rubygems/core_ext/kernel_require.rb:92:in `require'
         2: from /root/ruby-2.7.1/.ext/common/openssl.rb:13:in `<top (required)>'
         1: from /root/ruby-2.7.1/lib/rubygems/core_ext/kernel_require.rb:92:in `require'
/root/ruby-2.7.1/lib/rubygems/core_ext/kernel_require.rb:92:in `require': /root/ruby-2.7.1/.ext/x86_64-linux/openssl.so: symbol EC_GROUP_new_curve_GF2m, version OPENSSL_1_1_0 not defined in file libcrypto.so.1.1 with link time reference - /root/ruby-2.7.1/.ext/x86_64-linux/openssl.so (LoadError)
make: *** [do-install-nodoc] 错误 1
[root@localhost ruby-2.7.1]# vi /root/ruby-2.7.1/lib/rubygems/core_ext/kernel_require.rb

========
I download Ruby from https://github.com/ruby/ruby.git
Everything was OK at compile time, but there was an error after make install.
As shown above .....

I've tried all this, but it didn't work
For example:
    --with-openssl-dir=/usr
Specify openssl installation location ....

But the same mistake happened.

OpenSSL version is up to date:

```bash
OpenSSL 3.0.0-alpha3-dev  (Library: OpenSSL 3.0.0-alpha3-dev )
```

What should I do?
Please help me, thanks...

**Comment by MSP-Greg** [comment]
> OpenSSL 3.0.0-alpha3-dev

Unless you have a specific reason for using an alpha version of OpenSSL 3.0.0, I might suggest using  OpenSSL 1.1.1g.

Very few external applications are testing against OpenSSL 3.0.0, and Ruby 2.7 was released four month before openssl-3.0.0-alpha1.

**Comment by rhenium** [comment]
The error is most likely caused by mixed installations of OpenSSL. `EC_GROUP_new_curve_GF2m()` will not be used when unavailable - it is checked by `OPENSSL_NO_EC2M` macro on compile-time. However, a different installation was picked on runtime.

> OpenSSL 3.0.0-alpha3-dev  (Library: OpenSSL 3.0.0-alpha3-dev )

Ruby/OpenSSL is not compatible with OpenSSL 3.0 yet. OpenSSL 3.0 will introduce multiple incompatible changes from 1.1 but is still in an early preview stage.

**Comment by tea1111980** [comment]
> > OpenSSL 3.0.0-alpha3-dev
> 
> 除非您有使用Alpha版本的OpenSSL 3.0.0的特殊原因，否则我建议您使用OpenSSL 1.1.1g。
> 
> 当前很少有外部应用程序针对OpenSSL 3.0.0进行测试，并且Ruby 2.7在openssl-3.0.0-alpha1发行前四个月发布。



First of all, thank you for your reply.

OpenSSL used before `1.1.1g` This version has tried to install, but the same error is still prompted.

In this case, I decided to try `OpenSSL 3.0` Version, the result is the same error

**Comment by tea1111980** [comment]
Thank you! @MSP-Greg and @rhenium !


It's finally solved!

I have a question. `OpenSSL 1.1.1g` , which was also installed before, has not been compiled and installed by `Ruby v2.7.1` ?



After that, I uninstalled them all again, and then reinstalled and compiled them again. As a result, there was no error that OpenSSL `.so` could not be linked.

At last I succeeded!
