### ISSUE TITLE
Gemspec doesn't include extension

### ISSUE THREAD

**Issue by martinjos** [ruby/openssl#37]
At the moment, the Gemspec doesn't set `extensions`. As a result, when you install the gem, the extension doesn't get built. If I'm not mistaken (and unless there is something about this gem I haven't quite understood yet) I think the following line needs to be added to `openssl.gemspec`:

```
spec.extensions    = ["ext/openssl/extconf.rb"]
```

(http://guides.rubygems.org/specification-reference/#extensions)

I came across this while I was trying to get the openssl gem to work with [LibreSSL](https://github.com/libressl-portable/portable).

**Comment by zzak** [comment]
Oh, interesting.. thanks for the report!

Did you get an error message or warning when you tried to install the gem?

I'll see if I can reproduce it!

**Comment by martinjos** [comment]
There is no error message when you install the gem. It just installs without the .so file. As I understand it, this file needs to be rebuilt for the target platform, which normally happens at install time - which is why it isn't included in the gem (but the sources are).

Perhaps this normally doesn't cause a visible problem because it simply falls back on the .so file provided with the system. However, I needed to ensure that it was using a version of the .so file that was built against LibreSSL, while the system version was built against OpenSSL. For this, you need to specify "-- --with-cflags=... --with-ldflags=..." to gem install - but it's no good doing this if the gem doesn't build the library anyway.

**Comment by zzak** [comment]
Should be fixed now, thank you!
