### ISSUE TITLE
Fips mode set to false in tests

### ISSUE THREAD

**Issue by uCatu** [ruby/openssl#375]
Is there a real reason why fips is set to false?
https://github.com/ruby/openssl/blob/93213b2730a45fe997b8e581c64c42e13cd9abde/test/openssl/utils.rb#L8

**Comment by rhenium** [comment]
Yes. We can't properly test our bindings with FIPS mode enabled since it would disable all non-FIPS-approved algorithms.

Please see Ruby's bug tracker for the discussion and relevant commits. https://bugs.ruby-lang.org/issues/6946

**Comment by uCatu** [comment]
> Yes. We can't properly test our bindings with FIPS mode enabled since it would disable all non-FIPS-approved algorithms.
> 
> Please see Ruby's bug tracker for the discussion and relevant commits. https://bugs.ruby-lang.org/issues/6946

You are missing fundemental tests e.g:
```
OpenSSL.fips_mode = false
obj = OpenSSL::PKey.read File.read File.expand_path '../ca/private/ca.key.pem', __dir__
OpenSSL.fips_mode = true
objFips = OpenSSL::PKey.read File.read File.expand_path '../ca/private/ca.key.pem', __dir__
```
are not equal.

**Comment by rhenium** [comment]
Note that Ruby/OpenSSL is a Ruby binding to the OpenSSL library and does not implement cryptographic primitives itself.

That is, whether `OpenSSL.fips_mode` is set or not will not affect the behavior of Ruby/OpenSSL - the Ruby binding. It's out of scope for Ruby/OpenSSL's test suite to check how the OpenSSL library behaves.
