### ISSUE TITLE
Low level API call, crashing Ruby application

### ISSUE THREAD

**Issue by uCatu** [ruby/openssl#376]
Hi,
Using `Digest::SHA1.new` instead of `OpenSSL::Digest::SHA1.new` causing Ruby to crash, can we propogate Ruby Exception instead of crashing? 
`sha_locl.h(128): OpenSSL internal error, assertion failed: Low level API call to digest SHA1 forbidden in FIPS mode!`

Thanks,
Dvir

**Comment by rhenium** [comment]
::Digest is provided by a separate library, digest: https://github.com/ruby/ruby/tree/master/ext/digest (https://github.com/ruby/digest)

The low level API does not have a mechanism to report an error and thus is killing the process as a last resort. It should use the EVP API instead.
