### ISSUE TITLE
Error : OpenSSL::SSL::SSLError: certificate verify failed connect

### ISSUE THREAD

**Issue by shubhamjaincav** [ruby/openssl#378]
OpenSSL::SSL::SSLError: certificate verify failed connect at org/jruby/ext/openssl/SSLSocket.java:266

sample code :

@socket  = TCPSocket.new(@uri.host, @port)
@ssl_context = OpenSSL::SSL::SSLContext.new
@ssl_context.cert = OpenSSL::X509::Certificate.new(File.open("certificate.crt"))
@ssl_context.key = OpenSSL::PKey::RSA.new(File.open("certificate.key"))
@ssl_context.ssl_version = :TLSv1_2_client
@ssl_context.verify_mode = OpenSSL::SSL::VERIFY_PEER 
@ssl_socket = OpenSSL::SSL::SSLSocket.new(@socket, @ssl_context) 
@ssl_socket.sync_close = true
@ssl_socket.connect

any help on it, why am i getting such error on line @ssl_socket.connect

My aim is to connect with secure websocket.

**Comment by rhenium** [comment]
JRuby's openssl library is developed at a separate repository: https://github.com/jruby/jruby-openssl.

The verification error is because the code does not set the trusted CA certificates store to the OpenSSL::SSL::SSLContext with `@ssl_context.cert_store = <an instance of OpenSSL::X509::Store>`.

**Comment by shubhamjaincav** [comment]
Still getting error certificate verify failed connect after using.

cert_store = OpenSSL::X509::Store.new
cert_store.add_file 'certificate.pem'
@ssl_context.cert_store = cert_store
