### ISSUE TITLE
gem fails to update openssl from 2.1.2 to 2.2.0

### ISSUE THREAD

**Issue by rgoldberg** [ruby/openssl#385]
gem fails to update openssl from 2.1.2 to 2.2.0.

```bash
sudo -H gem update -n /usr/local/bin openssl
```

Outputs:

```bash
Updating installed gems
Updating openssl
Building native extensions. This could take a while...
ERROR:  Error installing openssl:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.6.0/gems/openssl-2.2.0/ext/openssl
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /Library/Ruby/Site/2.6.0 -r ./siteconf20200625-86744-1hc440r.rb extconf.rb
checking for t_open() in -lnsl... no
checking for socket() in -lsocket... no
checking for openssl/ssl.h... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/$(RUBY_BASE_NAME)
	--with-openssl-dir
	--with-openssl-include
	--without-openssl-include=${openssl-dir}/include
	--with-openssl-lib
	--without-openssl-lib=${openssl-dir}/lib
	--with-kerberos-dir
	--without-kerberos-dir
	--with-kerberos-include
	--without-kerberos-include=${kerberos-dir}/include
	--with-kerberos-lib
	--without-kerberos-lib=${kerberos-dir}/lib
	--with-debug
	--without-debug
	--enable-debug
	--disable-debug
	--with-nsllib
	--without-nsllib
	--with-socketlib
	--without-socketlib
	--with-openssl-config
	--without-openssl-config
	--with-pkg-config
	--without-pkg-config
extconf.rb:99:in `<main>': OpenSSL library could not be found. You might want to use --with-openssl-dir=<dir> option to specify the prefix where OpenSSL is installed. (RuntimeError)

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-19/2.6.0/openssl-2.2.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.6.0/gems/openssl-2.2.0 for inspection.
Results logged to /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-19/2.6.0/openssl-2.2.0/gem_make.out
Gems updated: openssl
```

Logs are attached.

[gem_make.out.txt](https://github.com/rubygems/rubygems/files/4831923/gem_make.out.txt)
[mkmf.log](https://github.com/rubygems/rubygems/files/4831924/mkmf.log)

I am running macOS 10.15.5 with XCode 11.5.  All other gems are up to date, and the rest of my software should be the latest stable or newer.  I'm using the Ruby supplied by macOS 10.15.5. I don't directly use Ruby myself, but I try to update all existing software on my system so I can get security patches, bug fixes, performance improvements, etc.

`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.Internal.sdk` doesn't exist.

`MacOSX10.15.sdk` exists in the parent of the nonexistent `MacOSX10.15.Internal.sdk`.

`MacOSX10.15.sdk` is a link to `MacOSX.sdk` in the same directory.

`usr/local/libressl/lib` doesn't exist in that directory because, while `usr` exists, it doesn't contain `local`.

Running `find . -iname '*libressl*'` in `MacOSX10.15.sdk` does not find any matching paths.

Running `find . -iname '*ssl.h*'` returns:

```
./usr/include/apache2/mod_ssl_openssl.h
./usr/include/apache2/mod_ssl.h
```

I was able to successfully upgrade using openssl installed via brew, like:

```bash
sudo -H gem update -n /usr/local/bin openssl -- --with-openssl-dir=/usr/local/Cellar/openssl@1.1/1.1.1g
```

See my issue that I opened with the Ruby Gems project: https://github.com/rubygems/rubygems/issues/3760

**Comment by rhenium** [comment]
As far as I know macOS no longer ships with OpenSSL header files that Apple used to compile the bundled Ruby, which are probably supposed to be in the `MacOSX10.15.Internal.sdk`. As such, openssl gem cannot find them on the system and fails to compile.

This is a decision made by Apple and we can't do anything about it.

> ```shell
> sudo -H gem update -n /usr/local/bin openssl -- --with-openssl-dir=/usr/local/Cellar/openssl@1.1/1.1.1g
> ```

This is the correct way to work around the problem - note that, however, the extension will link to Homebrew's OpenSSL and not the base system's.

**Comment by rgoldberg** [comment]
Shouldn't there be some sort of workaround message when the error occurs?

Or some way to have the gem either find the headers elsewhere or automatically download the headers?

e.g., if there's some OpenSSL home path env variable, the install could just use that.  Or it could look first for the Apple-supplied headers, then Homebrew, then Fink, then MacPorts, etc. (whatever common locations where the headers might be located).  It could even offer an option to select which headers, if more than one set is found.

It doesn't seem to make sense to leave it to end users to figure out, or ask, how to fix the problem.

**Comment by ryanpcmcquen** [comment]
Will this also work like this?
```
sudo -H gem update -n /usr/local/bin openssl -- --with-openssl-dir="$(brew --prefix openssl)"
```

**Comment by rgoldberg** [comment]
@ryanpcmcquen Yes, that should work.

But the real problem is that this issue occurs without a workaround being automatically applied or suggested in an error message.

**Comment by rhenium** [comment]
> ```
> extconf.rb:99:in `<main>': OpenSSL library could not be found. You might want to use --with-openssl-dir=<dir> option to specify the prefix where OpenSSL is installed. (RuntimeError)
> ```

The `--with-openssl-dir` is suggested in the error message. Homebrew's, or any other installation in non-standard locations, will not be automatically used (nor should be used without the user's confirmation, as they are not meant as a drop-in replacement of the macOS-bundled one). The issue here really is that Apple doesn't supply header files for the system libraries while C extensions are a big part of Ruby's ecosystem.

Personally, I recommend *against* using macOS-bundled Ruby and instead install it from Homebrew (or another package manager).

**Comment by rgoldberg** [comment]
I don't intentionally use the builtin Ruby.  I just update the existing software on my machine to stay current with patches, security & otherwise.

It seems like, in versions of XCode after a specific version, the headers won't ever be in the place that the gem specifies by default, so this gem will fail to install a lot.

It seems to me useful to check for the existence of the files before trying to reference them; if they don't exist, give people a nice warning instead of tons of logs obscuring the issue.  It's also worrying to have an error and be told to reference a prefix for OpenSSL when it worked previously; it makes you think you somehow broke your installation.  Also, the prefix concept wasn't defined here.  It would be nice to explain:

1. that the files are no longer distributed with XCode, so nothing is wrong, you just need to supply them yourself
2. what version of OpenSSL is best to use (presumably the latest 1.1.1*, but I don't know)
3. the relative path from the prefix path to the files that are used by the gem installation, so one can just search for the requisite files & obtain the prefix from their locations

**Comment by dfdgsdfg** [comment]
You have to install x86_64 Openssl from Brew. If you are using M1.

```bash
# install x86_64 brew
arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

# install x86_64 Openssl
arch -x86_64 /usr/local/brew install openssl@1.1

# export openssl path
arch -x86_64 

# install Ruby/Openssl

arch -x86_64  gem install openssl -- --with-openssl-dir=/usr/local/Cellar/openssl@1.1/1.1.1
```
