### ISSUE TITLE
X509::Store#verify incorrectly failing when two trusted certificates have matching subject names

### ISSUE THREAD

**Issue by santiagorodriguez96** [ruby/openssl#389]
Some days ago, we found a bug in our gem [tpm-key_attestation](https://github.com/cedarcode/tpm-key_attestation) that causes a certificate to not be trustworthy – in other words, method `X509::Store#verify` returns `false` – when it's signed by a root certificate that has the same subject name as other trusted root certificate.
Specifically, the two root certificates that we are using that have the same subject name (but different serial number) are [these two](https://github.com/cedarcode/tpm-key_attestation/tree/f71feccd086ed65bbfee2719b35c2aa3f5b3fe7d/lib/tpm/certificates/AMD/RootCA) – we got the from a collection of trusted TPM root and intermediate certificates [published by Microsoft](https://docs.microsoft.com/en-us/windows-server/security/guarded-fabric-shielded-vm/guarded-fabric-install-trusted-tpm-root-certificates).
Basically, in the specific case of our gem, when trying to check the trustworthiness of a certificate signed with the root certificate `AMD-fTPM-RSA-RootCA.crt`, the trust store, in its look up procedure, will verify against the other root certificate `AMD-fTPM-ECC-RootCA.crt` – since is the one that comes first in the array – eventually resulting in an error of invalid signature. But, if we remove the latter mentioned root certificate before verifying and leave only the one used to sign, the certificate will be considered trustworthy.

However, according to the documentation of the [verify method from openssl](https://www.openssl.org/docs/man1.1.0/man1/verify.html), this does not seem to be expected behavior since it says: 

>The process of 'looking up the issuers certificate' itself involves a number of steps. **After all certificates whose subject name matches the issuer name of the current certificate are subject to further tests**.

when in this case is not checking against all cases but rather returning false after the first one does not validate the signature.

Note: In our gem, we are testing against different versions of Ruby OpenSSL gem – `v2.0`, `v2.1` and `v2.2` –, OpenSSL library – `v1.0.2n` and `v1.1.1d` – and Ruby – `v2.7.1`, `v2.6.6`, `v2.5.8` and `v2.4.10` – and this bug is being reproduced in all cases.

**Comment by santiagorodriguez96** [comment]
I went ahead and [created a PR](https://github.com/ruby/openssl/pull/390) in an attempt to reproduce this bug, hope it helps!

**Comment by rhenium** [comment]
Interesting. I'm not sure if it is a bug or if it is just not implemented yet, though. OpenSSL generally follows RFC 5280 and CAs conforming to it should be generating the authorityKeyIdentifier extension, which would prevent the wrong path construction.

[RFC 5280 4.2.1.1.  Authority Key Identifier](https://tools.ietf.org/html/rfc5280#section-4.2.1.1) says:
>    The keyIdentifier field of the authorityKeyIdentifier extension MUST
   be included in all certificates generated by conforming CAs to
   facilitate certification path construction.  There is one exception;
   where a CA distributes its public key in the form of a "self-signed"
   certificate, the authority key identifier MAY be omitted.

Anyway, the path construction and the verification is entirely done by the OpenSSL library and Ruby/OpenSSL just uses it through X509_verify_cert(). This should be reported to them (https://github.com/openssl/openssl) instead.

**Comment by rhenium** [comment]
I took a glance through the OpenSSL code to find out that this is actually covered in the current master and 1.1.1 branch, which is not included in any release yet, however.

- master commit: https://github.com/openssl/openssl/commit/ffd2df135a5d9f6d2627bd125f362298430fdc06
- 1.1.1 backport: https://github.com/openssl/openssl/commit/e2590c3a162eb118c36b09c2168164283aa099b4
