### ISSUE TITLE
Test failures with LibreSSL

### ISSUE THREAD

**Issue by zzak** [ruby/openssl#40]
In b7c18e7 we added test support for LibreSSL, however I'm seeing 2 test failures:

```
Error: test_digest_constants(OpenSSL::TestDigest)
: RuntimeError: Unsupported digest algorithm (SHA).
/home/openssl/code/test/test_digest.rb:65:in `initialize'
/home/openssl/code/test/test_digest.rb:65:in `new'
/home/openssl/code/test/test_digest.rb:65:in `block in test_digest_constants'
     62:       algs += %w(SHA224 SHA256 SHA384 SHA512)
     63:     end
     64:     algs.each do |alg|
  => 65:       assert_not_nil(OpenSSL::Digest.new(alg))
     66:       klass = OpenSSL::Digest.const_get(alg)
     67:       assert_not_nil(klass.new)
     68:     end
/home/openssl/code/test/test_digest.rb:64:in `each'
/home/openssl/code/test/test_digest.rb:64:in `test_digest_constants'
```
This is the first error [from the build](https://travis-ci.org/ruby/openssl/jobs/93292789#L254).

Next:
```
Error: test_openssl_engine_digest_sha1(OpenSSL::TestEngine)
: OpenSSL::Engine::EngineError: unimplemented digest
/home/openssl/code/test/test_engine.rb:37:in `digest'
/home/openssl/code/test/test_engine.rb:37:in `test_openssl_engine_digest_sha1'
     34: 
     35:   def test_openssl_engine_digest_sha1
     36:     engine = get_engine
  => 37:     digest = engine.digest("SHA1")
     38:     assert_not_nil(digest)
     39:     data = "test"
     40:     assert_equal(OpenSSL::Digest::SHA1.digest(data), digest.digest(data))
```
Found [here](https://travis-ci.org/ruby/openssl/jobs/93292789#L271).

I'd like to resolve these and merge #36.

**Comment by zzak** [comment]
It looks like both of these test failures are due to unsupport/unimplemented openssl features in libressl.

So we probably just need to add some guards, either around these tests or whatever.

**Comment by nurse** [comment]
> Error: test_digest_constants(OpenSSL::TestDigest)
> : RuntimeError: Unsupported digest algorithm (SHA).

It is because [LibreSSL 2.3 removed SHA-0 support](https://github.com/libressl-portable/openbsd/commit/a35c259729689f7960598492bb39baf404b4abbd#diff-ae3e19bf4efe81ca4aafe508b48c654a). In openssl code, "SHA" means SHA-0. Therefore this failure is expected and should be ignored.

> Error: test_openssl_engine_digest_sha1(OpenSSL::TestEngine)
> : OpenSSL::Engine::EngineError: unimplemented digest

I seems LibreSSL 2.3's bug introduced by above commit. It defines OPENSSL_NO_SHA0. Because OpenSSL uses the macro to judge whether digest algorithm is used or not, they must remove it with the commit, but they missed [a condition](https://github.com/libressl-portable/openbsd/blob/master/src/lib/libssl/src/crypto/engine/eng_openssl.c#L108).

**Comment by nurse** [comment]
Sent PR to LibreSSL https://github.com/libressl-portable/openbsd/pull/57

**Comment by zzak** [comment]
@nurse Thank you for your investigation!

IWill adding a skip around `test_digest_constants` for LibreSSL work suffice?

**Comment by nurse** [comment]
> Will adding a skip around test_digest_constants for LibreSSL work suffice?

Yes only for "SHA". It must work others including "SHA1".
Maybe simply removing "SHA" from the test is fine.
How do you think, @nahi?

**Comment by nurse** [comment]
@zzak I committed 10eef96df4985d6e69f280b6ced4c567c20b5ca0 to ignore test_digest_constants

**Comment by zzak** [comment]
@nurse Thanks! I will merge here.
