### ISSUE TITLE
PKCS7 with multiple certs fails to decrypt randomly!

### ISSUE THREAD

**Issue by vihai** [ruby/openssl#400]
Hello,

I'm doing multiple-certificate encryption and decryption with pkcs7 routines and encryption/decryption fails randomly.
I attached a sample code that shows the problem. It generates two keypairs and two self-signed certificates, then encrypts and decrypts a string 1000 times and roughly 50% of the times the decryption fails with the same two certificates.

With one certificate it always work fine. With two, tre, four certificates the issue shows up.

```ruby
# ruby openssl_error.rb
good=497 bad=503
```

I then changed the code to encrypt once and decrypt 50000 times. Well, the result was surprising:

With two certificates:
```ruby
good=50000 bad=0
good=181 bad=49819
good=206 bad=49794
good=200 bad=49800
good=50000 bad=0
good=202 bad=49798
good=50000 bad=0
```

With four certificates:
```ruby
good=11104 bad=38896
good=10299 bad=39701
good=16004 bad=33996
good=13351 bad=36649
good=12753 bad=37247
good=14398 bad=35602
good=11730 bad=38270
good=12157 bad=37843
```

So, with some generated ciphertext the decryption is always successful. With some generated ciphertext the decryption is mostly (but not always) unsuccessful.

I was passing the certificate to decrypt since otherwise it was failing most of the time.

I then noticed that by default openssl was using RC2-CBS that is not a cipher one may want to use, so I specified AES-256-CBC with no improved.

Finally I removed the passing of the certificate to decrypt and in such configuration it seems to work.

However this random behavior may be hiding some major issue in memory management or corruption so you may want to know about it.

Tested on:
Ubuntu 20.02, ruby 2.7, openssl 2.2.0 (lib 1.1.1f)
Alpine 3.12, ruby 2.7, openssl 2.1.2 (lib 1.1.1g)
VM on Xeon
Native on AMD
[openssl_error.rb.txt](https://github.com/ruby/openssl/files/5131319/openssl_error.rb.txt)

**Comment by rhenium** [comment]
> ```ruby
>   cert = OpenSSL::X509::Certificate.new
>   cert.version = 2
>   cert.serial = 1
>   cert.subject = subject
>   cert.public_key = key.public_key
>   cert.not_before = Time.now
>   cert.not_after = Time.now + (360 * 24 * 3600)
> ```

This is an issue with the test program. The issuer field is missing in the generated certificates and they have the same serial number. As a result, OpenSSL::PKCS7#decrypt finds the wrong RecipientInfo in the PKCS #<span>7</span> structure, which is stored unordered (SET OF RecipientInfo).

**Comment by vihai** [comment]
Thank you, it makes sense, I got more concerned that it deserved, sorry for the misreporting :)
