### ISSUE TITLE
SSLContext cipher

### ISSUE THREAD

**Issue by Cybertron1** [ruby/openssl#403]
Hi,
I wrote following code which fetches the certificate chain from cloudflare.com. But Cloudflare has a hybrid system where old browser receive the RSA cert and the new clients receive the ECDSA cert (see https://www.ssllabs.com/ssltest/analyze.html?d=cloudflare.com&s=104.17.176.85).
In this case I want to get the older RSA certificate, that is why I set `ctx.ciphers = 'aRSA'`. But somehow I always receive the ECDSA certificate.
Following command works though `openssl s_client -cipher aRSA -connect cloudflare.com:443 -showcerts`. So it can be that I messed up somewhere.

```
ctx = OpenSSL::SSL::SSLContext.new
ctx.ciphers = 'aRSA'
sock = Socket.tcp("https://www.cloudflare.com", 443, connect_timeout: 10)
connection = connect(sock, ctx, hostname)
connection.peer_cert_chain

def connect(sock, ctx, url)
   ssl = OpenSSL::SSL::SSLSocket.new(sock, ctx)
   ssl.hostname = url
   begin
      ssl.connect_nonblock
   rescue IO::WaitReadable
      return nil unless IO.select([ssl], nil, nil, 10)

      retry
   rescue IO::WaitWritable
      return nil unless IO.select(nil, [ssl], nil, 10)

      retry
   end
   ssl
end
```

Thanks

Ruby Version: 2.6.3
Ruby OpenSSL Version: 2.2.0
OpenSSL Version: LibreSSL 2.8.3

**Comment by Cybertron1** [comment]
I was able to get the old RSA certificate chain with:
```
ctx.max_version = :TLS1_2
ctx.ciphers = 'aRSA'
```

**Comment by ioquatix** [comment]
Thanks for following up with a solution.
