### ISSUE TITLE
OpenSSL::Timestamp is not working on openssl 2.2.0 gem (uninitialized constant OpenSSL::Timestamp)

### ISSUE THREAD

**Issue by yehgold** [ruby/openssl#410]
Windows, Ruby 2.6.5, openssl 2.2.0 (same goes for 2.1.2)
OpenSSL::Timestamp is failing with the error: 

 uninitialized constant OpenSSL::Timestamp

This happens with all OpenSSL::Timestamp. 

OpenSSL::Timestamp::TokenInfo
OpenSSL::Timestamp::Request
OpenSSL::Timestamp::Response
OpenSSL::Timestamp::Factory

**Comment by rhenium** [comment]
Sorry for the slow response.

OpenSSL::Timestamp was newly added by openssl gem v2.2.0 and the constant should exist.

Please check the value of `OpenSSL::VERSION` to see if v2.2.0 (from RubyGems) is loaded properly, not v2.1.2 (bundled by Ruby 2.6.5).

**Comment by rhenium** [comment]
Closing this issue.
