### ISSUE TITLE
Actions - Test failures with macOS Big Sur & 1.1.1h

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/openssl#411]
Had an issue in another repo that compiles with OpenSSL, and tried updating the CI here to use Ubuntu 20.04 and macOS 11.0 (Big Sur?).  All the macOS jobs using 1.1.1h failed with:
```
1) Failure: test_verify_callback(OpenSSL::TestX509Store)
/Users/runner/work/ruby-openssl/ruby-openssl/test/openssl/test_x509store.rb:124:in `test_verify_callback'
     121:     }
     122:     store.add_cert(ca1_cert)
     123:     assert_equal(true, store.verify(ee1_cert, [ca2_cert]))
  => 124:     assert_equal(3, cb_calls.size)
     125:     assert_equal([true, ca1_cert], cb_calls[0])
     126:     assert_equal([true, ca2_cert], cb_calls[1])
     127:     assert_equal([true, ee1_cert], cb_calls[2])
<3> expected but was
<2>
```

Some of the later Windows jobs also failed.  See:

https://github.com/MSP-Greg/ruby-openssl/actions/runs/394960080

Note that all the Ubuntu 20.04 jobs passed...

**Comment by rhenium** [comment]
Sorry for the slow response.

This was probably due to a bug in OpenSSL 1.1.1h, which apparently excluded certificates in the trusted store (`ca1_cert`) from the verification process.

From https://github.com/openssl/openssl/blob/90cebd1b216e0a160fcfd8e0eddca47dad47c183/CHANGES:
> ```
>  Changes between 1.1.1h and 1.1.1i [8 Dec 2020]
> [...]
>   *) In 1.1.1h, an expired trusted (root) certificate was not anymore rejected
>      when validating a certificate path. This check is restored in 1.1.1i.
>      [David von Oheimb]
> ```
