### ISSUE TITLE
Cut 2.3.0 or 2.2.1 release for Ruby 3.0

### ISSUE THREAD

**Issue by hsbt** [ruby/openssl#412]
@rhenium Do you have a plan to release 2.3.0 from master or minor release of 2.2.1?

I'm happy to merge the latest version of openssl to ruby master branch as Ruby 3.0.

**Comment by ioquatix** [comment]
There are enough features it should probably be 2.3.0 IMHO and yes we should cut a new release for Ruby 3.0 if possible.

**Comment by hsbt** [comment]
We postponed to release new version from the current master branch.
