### ISSUE TITLE
CSR sample doesn't work out of the box

### ISSUE THREAD

**Issue by toabi** [ruby/openssl#419]
https://github.com/ruby/openssl/blob/bd9f5c301716afe7e333f148dcbd2dfe56df2bb0/sample/gen_csr.rb#L44

This fails with not finding `Digest`.

But it works when writing `OpenSSL::Digest.new("MD5")`. But I never used ruby before.

**Comment by rhenium** [comment]
Good catch. The use of `include OpenSSL` in those examples is problematic.

**Comment by toabi** [comment]
You wouldn't believe it but the existence of this sample and the fix that it's working now saved some part on infrastructure from collapse :D Because with this library one can create CA certificates where the country has three letters. 🥳
