### ISSUE TITLE
ED25519 support

### ISSUE THREAD

**Issue by tambry** [ruby/openssl#443]
1. `openssl genpkey -algorithm ED25519 -out test.key`
2. `ruby -e "require 'openssl'; OpenSSL::PKey::EC.new('test.key')"` fails with "invalid curve name"

The failure is somewhat expected as ED25519 keys aren't EC keys (they don't have a choice of curves) and this holds also for X25519, X448 and ED448.

This is preventing me from using an internal ED25519-based CA with Puppet.

Say I were interested in implementing them (or at least ED25519) would it be just appropriate to create more key types for each, analogous to the existing ones?

**Comment by rhenium** [comment]
Yes, OpenSSL handles Ed25519 separately in the EVP layer - `EVP_PKEY_ED25519` vs `EVP_PKEY_EC`, so it doesn't belong to OpenSSL::PKey::EC.

Basic support for Ed25519 and X25519 is implemented by #370/#329 (please see the test code for Ed25519/X25519 example). It's currently only in master and not part of a release yet.

**Comment by rhenium** [comment]
This is part of openssl v3.0.0.

https://github.com/ruby/openssl/blob/d36e6e5ef70917c5cb8f58a0c27f9eb6e583dc9a/History.md#notable-changes

**Comment by joshcooper** [comment]
I submitted https://github.com/ruby/openssl/pull/804 to allow requests to be signed using ED25519
