### ISSUE TITLE
Print openssl library version in travis config

### ISSUE THREAD

**Issue by zzak** [ruby/openssl#46]
I'd like to know exactly which version we've compiled against in the build logs to help with debugging.

**Comment by patcon** [comment]
Hey @zzak, may I asked why you closed this? Seems like a great idea, as I'm hitting something like this with `travis encrypt-file` command: https://stackoverflow.com/questions/34304570/how-to-resolve-the-evp-decryptfinal-ex-bad-decrypt-during-file-decryption
