### ISSUE TITLE
New feature request: the ability for the user to set TLS 1.3 ciphersuites

### ISSUE THREAD

**Issue by twkmd12** [ruby/openssl#476]
Hello,

I have a request for a simple feature: the ability for the user to set TLS 1.3 ciphersuites. If nobody is available, I can do it and submit the changes.

Thank you!

**Comment by rhenium** [comment]
This is currently not supported. We would need to add a wrapper for `SSL_CTX_set_ciphersuites()` for this.

**Comment by twkmd12** [comment]
Yes. I understand it's not supported. Do you have any objections to me implementing it?

**Comment by twkmd12** [comment]
@rhenium I want to make sure there will be no objections to me submitting a patch for this feature. Assuming you're happy with the code, is this a feature you'd be willing to accept? Please confirm.
