### ISSUE TITLE
Q size changed for DSA parameters in version 3

### ISSUE THREAD

**Issue by vcsjones** [ruby/openssl#483]
👋 hello, I wanted to inquire about a behavioral change I noticed in version 3 for DSA key generation, namely that the Q parameter has changed from 160-bit to 224-bit:

```ruby
require 'openssl'
pkey = OpenSSL::PKey::DSA.generate(1024)
puts pkey.params['q'].num_bits
```

In version 2.2.0, this would print `160`. In 3.0.0, this prints `224`. The size of Q directly impacts the size of DSA signatures, so version 3 is now making larger DSA signatures by default without changing the key size.

Note, I can work around this now by explicitly setting the number of Q bits:

```ruby
dsa_parameters = OpenSSL::PKey.generate_parameters("DSA", {
  dsa_paramgen_bits: 1024,
  dsa_paramgen_q_bits: 160,
})

pkey = OpenSSL::PKey.generate_key(dsa_parameters)
puts pkey.params['q'].num_bits
```

I find it slightly odd that the Q and signature size changed for 1024-bit DSA. If this is expected or intentional, then please feel free to close the issue indicating as such since there is an appropriate API to set Q back to 160 bits.

**Comment by rhenium** [comment]
This is not an intentional change.

I thought parameters generation via `EVP_PKEY_paramgen()` would behave the same way as `DSA_generator_parameters_ex()`, but apparently it didn't.

I'll make a PR to restore the original behavior.
