### ISSUE TITLE
`OpenSSL::TestPKey#test_s_generate_parameters` random failures

### ISSUE THREAD

**Issue by voxik** [ruby/openssl#492]
Testing with Ruby 3.1, the Ruby test suite sometimes fails with the following error:

~~~
  1) Failure:
OpenSSL::TestPKey#test_s_generate_parameters [/builddir/build/BUILD/ruby-3.1.0/test/openssl/test_pkey.rb:44]:
RuntimeError expected but nothing was raised.
~~~

**Comment by rhenium** [comment]
Is this with OpenSSL 3.0? Your comment in 2021-11 on the same failure: https://github.com/ruby/openssl/pull/399#issuecomment-963935021

I haven't been able to reproduce it locally.

**Comment by voxik** [comment]
> Is this with OpenSSL 3.0?

Yes, Ruby 3.1 with OpenSSL 3.0

> Your comment in 2021-11 on the same failure: [#399 (comment)](https://github.com/ruby/openssl/pull/399#issuecomment-963935021)

Ah, right, sorry, I have already forgotten about that remark. But at that time, I was not sure it is not issue with the patches backported to Ruby 3.0.2. Now it is with Ruby 3.1, so is likely not my fault (although who knows :wink:)

> I haven't been able to reproduce it locally.

Unfortunately, it fails just from time to time and I don't have better reproducer at hand :/

**Comment by rhenium** [comment]
Running the test file repeatedly was enough to reproduce it: `while ruby -Ilib -Itest/openssl test/openssl/test_pkey.rb; do :; done`

It turned out to be an issue in the current OpenSSL 3.0.x. https://github.com/openssl/openssl/pull/19314
