### ISSUE TITLE
Cannot locate symbol ASN1_TIME_free

### ISSUE THREAD

**Issue by e2002e** [ruby/openssl#497]
I'm compiling ruby 2.7, had problems when checked out v2_7_6 (i realized that we must checkout "ruby_2_7" right ?).
It compiles but when running gem:
Cannot locate symbol ASN1_TIME_free

grep -R ASN1_TIME_free ruby/.ext/arm-linux-androideabi/openssl.so 
grep: ruby/.ext/arm-linux-androideabi/openssl.so: binary file matches

What's wrong with the linkage ? I'm using android ndk to build openssl.so (shared) and tried to link with libssl and libcrypto both statically and shared.
I had succeeded to make it work but mixed brushes when pushing to github and then pulling on another PC (then pushing again from here, and pulling on the original working station).

**Comment by rhenium** [comment]
`ASN1_TIME_free()` is a public API of libcrypto and should exist in all recent OpenSSL versions.

The error message suggests that an ABI-incompatible version of libcrypto was picked up on runtime.

> I had succeeded to make it work but mixed brushes when pushing to github and then pulling on another PC (then pushing again from here, and pulling on the original working station).

This would happen if the original workstation and the another PC don't have the same setup with the same version of OpenSSL/libcrypto.

**Comment by e2002e** [comment]
Thank you for the hint.
