### ISSUE TITLE
RSA private key export passphrase cannot start with \0

### ISSUE THREAD

**Issue by andrei-mihaila** [ruby/openssl#51]
Hi,

This is rather a request for clarification.

In my application I'm using a key derived from a passphrase when exporting the RSA key of some user. Something like:

```ruby
require 'openssl'

rsa_key = OpenSSL::PKey::RSA.new 3072

digest = OpenSSL::Digest.new('SHA384')
salt = OpenSSL::Random.random_bytes(16)
length = digest.digest_length
hashed = OpenSSL::PKCS5.pbkdf2_hmac('some passphrase', salt, 2000, length, digest)

secured = rsa_key.export OpenSSL::Cipher::new('AES-256-CBC'), hashed
```

Sometimes (depending on the salt) the value returned by `OpenSSL::PKCS5.pbkdf2_hmac` starts with `\0` and I get an exception:
```
in `export': read key (OpenSSL::PKey::RSAError)
```

Is this normal behaviour or is it a bug? I think the export function just uses a cipher to encrypt the RSA key. And the cipher itself can take a string that starts with `\0` as a key ... so shouldn't the export function work the same? Or should I always encode the passphrase sent to `export` (for example with `Base64.encode64`)?

Here is a simple way to make `export` raise the error (in case this is actually a bug and you want to add a test for it):
```ruby
require 'openssl'

rsa_key = OpenSSL::PKey::RSA.new 512

secured = rsa_key.export OpenSSL::Cipher::new('AES-128-CBC'), "\x00123"
```

Thanks!

**Comment by rhenium** [comment]
Thank you for reporting!
This is a bug. Null character should be accepted in the password. Even if it were null character unsafe, it should at least raise an exception with a meaningful message.

r55087 (ruby/ruby@f52ab6e4940f9095c4fc5e2f7860bd56747f1c7c) will fix this.
