### ISSUE TITLE
`public_key=': wrong argument type OpenSSL/EC_POINT (expected OpenSSL/EVP_PKEY) (TypeError)

### ISSUE THREAD

**Issue by marek22k** [ruby/openssl#533]
Hello,

I am creating an X509 certificate and assigning the public key from an EC key. Then this error appears. With RSA key this does not happen. I have seen that the error is already reported in https://github.com/ruby/openssl/issues/29, but not fixed, but the issue is closed.

```ruby
require "openssl"

key = OpenSSL::PKey::EC.new "secp521r1"
cert = OpenSSL::X509::Certificate.new
cert.version = 2
cert.serial = Random.rand(2**16 - 2) + 1

cert.subject = OpenSSL::X509::Name.new [["CN", "localhost"], ["emailAddress", "postmaster@localhost"]]
cert.issuer = cert.subject  # self-signed certificate
cert.public_key = key.public_key
```
results in
```
`public_key=': wrong argument type nil (expected OpenSSL/EVP_PKEY) (TypeError)
```

**Comment by rhenium** [comment]
> I have seen that the error is already reported in #29, but not fixed, but the issue is closed.

It is unfortunate the `#public_key` method on EC was assigned a different function than on RSA/DSA/DH, but RSA/DSA/DH's `#public_key` was not particularly useful.

https://ruby.github.io/openssl/OpenSSL/PKey/RSA.html#method-i-public_key

---

As mentioned in the issue, you can directly pass the OpenSSL::PKey::PKey instance to OpenSSL::X509::Certificate#public_key=.

```ruby
cert.public_key = key
```

**Comment by marek22k** [comment]
So, to my understanding, this is due to OpenSSL itself and not Ruby? If I put the key directly in the certificate, isn't there a risk that my private key will somehow be included in the certificate?

**Comment by marek22k** [comment]
@rhenium So, to my understanding, this is due to OpenSSL itself and not Ruby? If I put the key directly in the certificate, isn't there a risk that my private key will somehow be included in the certificate?

**Comment by rhenium** [comment]
OpenSSL::X509::Certificate#public_key= sets the Subject Public Key Info field of a certificate. The encoding used by that field can't accidentally store any private key components, so that is safe. https://datatracker.ietf.org/doc/html/rfc5280#section-4.1.2.7

Note that a private key in OpenSSL can always also act as the corresponding public key.
