### ISSUE TITLE
Can't install openssl in ruby@2.7.6

### ISSUE THREAD

**Issue by m11o** [ruby/openssl#534]
Hi!

I tried to install openssl to use [shopify_api](https://github.com/Shopify/shopify-api-ruby) gem.
But, error occured and it wasn't installed. Detail of error is following.

```
$ bundle install

...
Installing openssl 3.0.0 with native extensions

compiling ossl_ts.c
In file included from ossl_ts.c:10:
In file included from ./ossl.h:171:
./openssl_missing.h:195:11: warning: 'TS_VERIFY_CTS_set_certs' macro redefined [-Wmacro-redefined]
#  define TS_VERIFY_CTS_set_certs(ctx, crts) ((ctx)->certs=(crts))
          ^
/opt/homebrew/Cellar/openssl@3/3.0.5/include/openssl/ts.h:424:11: note: previous definition is here
#  define TS_VERIFY_CTS_set_certs(ctx, cert) TS_VERIFY_CTX_set_certs(ctx,cert)
          ^
ossl_ts.c:829:5: error: incomplete definition of type 'struct TS_verify_ctx'
    TS_VERIFY_CTX_set_certs(ctx, x509inter);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./openssl_missing.h:215:46: note: expanded from macro 'TS_VERIFY_CTX_set_certs'
#  define TS_VERIFY_CTX_set_certs(ctx, crts) TS_VERIFY_CTS_set_certs(ctx, crts)
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./openssl_missing.h:195:52: note: expanded from macro 'TS_VERIFY_CTS_set_certs'
#  define TS_VERIFY_CTS_set_certs(ctx, crts) ((ctx)->certs=(crts))
                                              ~~~~~^
/opt/homebrew/Cellar/openssl@3/3.0.5/include/openssl/ts.h:405:16: note: forward declaration of 'struct TS_verify_ctx'
typedef struct TS_verify_ctx TS_VERIFY_CTX;
               ^
1 warning and 1 error generated.
make: *** [ossl_ts.o] Error 1
```

I installed openssl@3 in my computer from homebrew.

```shell
$ brew list | grep openssl
openssl@1.1
openssl@3
```

ruby version:

```shell
$ ruby -v
ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [arm64-darwin21]
```

Would you please tell me how I can install it?
Thank you for your help!

**Comment by rhenium** [comment]
Please attach the content of `mkmf.log` file.

> ```
> ./openssl_missing.h:195:11: warning: 'TS_VERIFY_CTS_set_certs' macro redefined [-Wmacro-redefined]
> #  define TS_VERIFY_CTS_set_certs(ctx, crts) ((ctx)->certs=(crts))
> ```

From a quick glance at this error, it seems like a case where our extconf.rb and ossl_ts.c find the OpenSSL header files of different versions for some reason.

**Comment by m11o** [comment]
Hi! @rhenium 

Thank you for your replying.
I attached `mkmf.log` at this comment.
it's very long and it may be hard to read it. Please check it!

Thanks
[mkmf.log](https://github.com/ruby/openssl/files/9307687/mkmf.log)

**Comment by rhenium** [comment]
```
"clang -o conftest [...] -I/Users/m11o/.rbenv/versions/2.7.6/openssl/include [...]
```

```
| pkg-config --cflags-only-I openssl
=> "-I/opt/homebrew/Cellar/openssl@3/3.0.5/include\n"
| pkg-config --cflags-only-other openssl
=> "\n"
| pkg-config --libs-only-l openssl
=> "-lssl -lcrypto\n"
package configuration for openssl
incflags: -I/opt/homebrew/Cellar/openssl@3/3.0.5/include
cflags: 
ldflags: -L/opt/homebrew/Cellar/openssl@3/3.0.5/lib
libs: -lssl -lcrypto
```

---

This appears to be #486. The bugfix is not included in a release yet.

For the time being, I think you can give an environment variable `PKG_CONFIG_PATH=/Users/m11o/.rbenv/versions/2.7.6/openssl/lib/pkgconfig` to override `pkg-config`'s behavior, or add to Gemfile:

```ruby
gem "openssl", git: "https://github.com/ruby/openssl", ref: "e9798b1ec794d0c8f0a591b320ebb45afb037b52"
```

**Comment by m11o** [comment]
Great! It's resolved.
I appreciate for your help and look forward to the release.

**Comment by steakknife** [comment]
Please release this. Can't install ruby 3.1.3.

**Comment by hsbt** [comment]
Ruby 3.1.3 contains this fix https://github.com/ruby/ruby/commit/b3969f769a40e09ce5307b58ac78fa732c398aad.
