### ISSUE TITLE
Release a new version for Ruby 3.2

### ISSUE THREAD

**Issue by hsbt** [ruby/openssl#577]
@rhenium 

👋 Can you cut a new version of openssl gem for Ruby 3.2? It's great to merge https://github.com/ruby/openssl/pull/576 for it.

And I can help to release for this.

**Comment by hsbt** [comment]
@rhenium How about this progress?

We have only 3 days. I'll release `openssl-3.1.0.pre` from the current HEAD at 12/24 if you didn't have enough time for releasing.

**Comment by rhenium** [comment]
I am sorry for the trouble. I will try to make it soon.

**Comment by hsbt** [comment]
🙏  Sorry to rush request and thanks for your effort.

**Comment by rhenium** [comment]
I've released v3.1.0 from master (along with v3.0.2 and v2.2.3 which include bug fixes only). ruby/ruby is also updated with it.

Hope it works!

**Comment by hsbt** [comment]
Thanks! I'll test it on ruby repo with them.
