### ISSUE TITLE
Ruby 3.1, Ruby OpenSSL 3.0

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/openssl#588]
I believe Ruby 3.1.0 was released with Ruby/OpenSSL 3.0.0.  Ruby 3.1.3 is using Ruby/OpenSSL 3.0.1.  Current Ruby/OpenSSL 3.0.x release is 3.0.2.

Will Ruby 3.1.x releases contain the most recent version of Ruby/OpenSSL 3.0.x?

Also, History.md states 'Ruby/OpenSSL 3.1 will be maintained for the lifetime of Ruby 3.2.'

Would the same be true for 'Ruby/OpenSSL 3.0 will be maintained for the lifetime of Ruby 3.1'?

Given that OpenSSL 1.1.1 is EOL after 11-Sept-2023...

Happy New Year and thanks for all your work!

**Comment by rhenium** [comment]
Happy New Year!

> Will Ruby 3.1.x releases contain the most recent version of Ruby/OpenSSL 3.0.x?

Yes, it should, at least until Ruby 3.1 enters a security-fix-only mode (2024-03~?). After that, even if we release a new gem, it will not be merged into ruby/ruby, unless the changes are security fixes only. I think this is the general policy for all default/bundled gems.

> Also, History.md states 'Ruby/OpenSSL 3.1 will be maintained for the lifetime of Ruby 3.2.'
> 
> Would the same be true for 'Ruby/OpenSSL 3.0 will be maintained for the lifetime of Ruby 3.1'?

Yes. Ruby/OpenSSL 2.2 is still maintained for Ruby 3.0, too.

> Given that OpenSSL 1.1.1 is EOL after 11-Sept-2023...

I'm not sure how this affects us. We will eventually start to require OpenSSL 3.0 or later, but it will only happen in the master branch and will not be backported.

**Comment by junaruga** [comment]
Note that Ruby/OpenSSL versions are currently 3.0.1 in ruby_3_1 branch, and 3.1.0 in ruby_3_2 branch.

* https://github.com/ruby/ruby/blob/ruby_3_1/ext/openssl/lib/openssl/version.rb
* https://github.com/ruby/ruby/blob/ruby_3_2/ext/openssl/lib/openssl/version.rb

**Comment by rhenium** [comment]
I believe this is answered. Also, README was recently updated to include more information about the maintenance status.
