### ISSUE TITLE
Can't compile - missing underscore macro

### ISSUE THREAD

**Issue by chrisseaton** [ruby/openssl#64]
I'm working on a new alternative implementation of Ruby, and I'm trying to write compatible Ruby API headers for implementation and to use them to compile and run the OpenSSL gem.

One thing that I am having trouble with is your use of what I think is some kind of macro named `_`

https://github.com/ruby/openssl/blob/e1361a0aae241e0426b91d3d864c8628e1fa94f5/ext/openssl/ossl_pkey_dsa.c#L390

It's used around parameters in function pointer types in a few places. I can get it work by defining

```c
#define _(x) x
```

But I can't see anything like this in the MRI source code or the source code of this gem.

Is it maybe some C feature I don't know about? Something set in some configuration system? Something I'm not searching for well enough?

**Comment by rhenium** [comment]
_() macro is defined in Ruby's include/ruby/defines.h. It seems it was first added in 1998, for C compilers that don't support ANSI style function prototypes.

https://github.com/ruby/ruby/blob/c3236250fe404863297e55dbc28f218bf6c6091e/include/ruby/defines.h#L151

Ruby no longer compiles with such compilers so I just removed them at a45704f80884. Thanks!
