### ISSUE TITLE
New OpenSSL gem release

### ISSUE THREAD

**Issue by tcordeu** [ruby/openssl#651]
Good morning, we are currently using some features introduced in https://github.com/ruby/openssl/commit/189c167e4033f8923a12432e01f8f11345f22f48. Do you have any plans on releasing a new version in the short term?

Thanks,
Thomas.

**Comment by rhenium** [comment]
Agreed. This is long overdue.

**Comment by rhenium** [comment]
openssl v3.2.0 is available on rubygems.org now.

https://rubygems.org/gems/openssl/versions/3.2.0

**Comment by junaruga** [comment]
Thank you!
