### ISSUE TITLE
Automated sync to ruby/ruby repo

### ISSUE THREAD

**Issue by hsbt** [ruby/openssl#680]
@rhenium I and @k0kubun maintain that code sync between `ruby/*` and `ruby/ruby`. It's helpful to test with each commit of ruby/ruby repo.

I can prepare its configuration to ruby/openssl repo. How about this?

**Comment by rhenium** [comment]
I notice you manually run the sync script occasionally. Thank you for that.

If I understand correctly, this is about synchronizing ruby/openssl -> ruby/ruby and not the other way around. Yes, I appreciate it if it can be automated!

**Comment by hsbt** [comment]
@rhenium Thank you. I added webhook to this repo for auto-sync.
