### ISSUE TITLE
ruby >=2.3 - is it really necessary? How about 2.2?

### ISSUE THREAD

**Issue by aagorelik** [ruby/openssl#70]
Hi guys!

I use your lib in my project, but production env is ruby 2.2 and cannot be changed.
Does it really matters? I assume I can download a source code, edit gemspec and build my own gem? Or it won't work?

Thanks in advance!

**Comment by aagorelik** [comment]
Yup. Blind try to switch version in ```gemspec``:
```
dyld: lazy symbol binding failed: Symbol not found: _RB_FIXNUM_P
  Referenced from: /.../.rvm/gems/ruby-2.2.4/gems/openssl-2.0.0.beta.1/lib/openssl.bundle
  Expected in: flat namespace

dyld: Symbol not found: _RB_FIXNUM_P
  Referenced from: /.../.rvm/gems/ruby-2.2.4/gems/openssl-2.0.0.beta.1/lib/openssl.bundle
  Expected in: flat namespace
```

So it is important :) Any plans to support 2.2?

**Comment by rhenium** [comment]
Yes, besides the RB_FIXNUM_P, the test suite utilizes some of the Ruby 2.3 features. Actually the main target of the gem is Ruby >= 2.4 so there are no plans support even older versions.
