### ISSUE TITLE
It should be possible to provide AEAD TAG after data but before finish

### ISSUE THREAD

**Issue by cmouse** [ruby/openssl#74]
In some cases, most notably if you are streaming data over TCP, AEAD TAG cannot be provided until data has been transmitted. Yet, ruby openssl bindings unnecessarely insist that tag is provided before data. Can you please relax the requirements to require tag only before call to finish?

**Comment by rhenium** [comment]
It seems it actually works if I set the expected tag just before calling Cipher#final, but the documentation of the OpenSSL API still says so:

"GCM-and-OCB-Modes" in https://www.openssl.org/docs/manmaster/crypto/EVP_EncryptInit.html:

>     EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_AEAD_SET_TAG, taglen, tag);
> Sets the expected tag to taglen bytes from tag. This call is only legal when decrypting data and must be made before any data is processed (e.g. before any EVP_DecryptUpdate() call). For OCB mode the taglen must either be 16 or the value previously set via EVP_CTRL_AEAD_SET_TAG.

If this is incorrect, I think the OpenSSL's documentation should be fixed first.

**Comment by cmouse** [comment]
Hi!

Sorry for delay in response, I will try to raise issue on OpenSSL project about this.

**Comment by rhenium** [comment]
The upstream documentation has been corrected[1], and I've committed the change as https://github.com/ruby/openssl/commit/5f79da4812d2bafd92a964a63875cda8f76a8045. Thanks.

[1] https://www.openssl.org/docs/manmaster/man3/EVP_EncryptInit.html#GCM-and-OCB-Modes
