### ISSUE TITLE
Can we please cut a 3.3.0 release?

### ISSUE THREAD

**Issue by ioquatix** [ruby/openssl#741]
There are many interface fixes that forward to the underlying IO which I'd like to take advantage of.

**Comment by rhenium** [comment]
Agreed. I will try to check remaining open issues soon.

**Comment by nogweii** [comment]
Another vote for a 3.3.0 release. In my case I have need to sign using an Ed25519 key and the recently merged #761 adds support for that.

**Comment by bdewater** [comment]
With the next Ruby version soon, now might be a good time?

**Comment by hsbt** [comment]
@rhenium Thank you for maintaining always. I'm preparing to final release of Ruby 3.4.

Could you consider to release openssl 3.3.0 while recent weeks?

**Comment by junaruga** [comment]
The openssl gem 3.2.1 was released! https://github.com/ruby/openssl/pull/815#issuecomment-2551288097

**Comment by rhenium** [comment]
I'm sorry it took so long. I'm preparing the changelog for v3.3.

**Comment by rhenium** [comment]
https://github.com/ruby/openssl/pull/827

I've pushed v3.3.0 to rubygems.org.
