### ISSUE TITLE
openssl-head: OpenSSL::X509::RequestError: X509_REQ_set_version: passed invalid argument

### ISSUE THREAD

**Issue by junaruga** [ruby/openssl#746]
The following error appeared in the openssl-head (openssl 3.4.0-dev) cases with the latest openssl/openssl master branch commit https://github.com/openssl/openssl/commit/264ff64b9443e60c7c93af0ced2b22fdf622d179.

https://github.com/ruby/openssl/actions/runs/8813410629/job/24191105033?pr=745#step:12:624

```
 2) Error: test_version(OpenSSL::TestX509Request): OpenSSL::X509::RequestError: X509_REQ_set_version: passed invalid argument
/home/runner/work/openssl/openssl/test/openssl/test_x509req.rb:18:in `version='
/home/runner/work/openssl/openssl/test/openssl/test_x509req.rb:18:in `issue_csr'
/home/runner/work/openssl/openssl/test/openssl/test_x509req.rb:43:in `test_version'
     40:     req = OpenSSL::X509::Request.new(req.to_der)
     41:     assert_equal(0, req.version)
     42: 
  => 43:     req = issue_csr(1, @dn, @rsa1024, OpenSSL::Digest.new('SHA256'))
     44:     assert_equal(1, req.version)
     45:     req = OpenSSL::X509::Request.new(req.to_der)
     46:     assert_equal(1, req.version)
```

As a note, previously the error didn't happen in the openssl-head cases with the openssl/openssl master branch commit https://github.com/openssl/openssl/commit/1967539e212c17139dc810096da987c8100b1ba2.

**Comment by botovq** [comment]
See #734 and #747

**Comment by junaruga** [comment]
@botovq thanks for the PR!

**Comment by rhenium** [comment]
GitHub Actions is green with #747. Thank you!
