### ISSUE TITLE
Self-signed cert being ignored in Docker | Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate

### ISSUE THREAD

**Issue by RailsCod3rFuture** [ruby/openssl#749]
I'm using registry.docker.com/library/ruby:2.7.7-slim for building my docker image...The issue is; the SSL_CERT_FILE env var is not being complied with -- while running bundle install. I tried copying over the cert to ca-certificates...but that also got ignored. Do you have a method for verifying self-signed certificates in docker images?

**Comment by rhenium** [comment]
`SSL_CERT_FILE` is supposed to be handled by OpenSSL by default. I can't tell what is happening without more details.

Note that Ruby 2.7 is EOL. Please upgrade to Ruby 3.1 or later. https://www.ruby-lang.org/en/downloads/branches/

**Comment by RailsCod3rFuture** [comment]
I'll show what my dockerfile looks like. The main issue is that it does not pickup the fact that I've added a private cert before running bundle install.

`# syntax = docker/dockerfile:1

# Make sure RUBY_VERSION matches the Ruby version in .ruby-version and Gemfile
ARG RUBY_VERSION=2.7.7
FROM registry.docker.com/library/ruby:$RUBY_VERSION as base

WORKDIR /web-app

ENV RAILS_ENV="development" \
  BUNDLE_WITHOUT=""
RUN apt-get update -qq && \
  apt-get install --no-install-recommends -y build-essential git libvips pkg-config mariadb-client yarn nodejs ca-certificates
COPY CUSTOM_CERT_SubCA_1.crt /usr/local/share/ca-certificates/CUSTOM_CERT_SubCA_1.crt
ENV SSL_CERT_FILE=/usr/local/share/ca-certificates/CUSTOM_CERT_SubCA_1.crt
RUN chmod 644 /usr/local/share/ca-certificates/CUSTOM_CERT_SubCA_1.crt && update-ca-certificates
COPY Gemfile Gemfile.lock ./
RUN mkdir -p /vendor/rails_7_gems
COPY vendor/rails_7_gems/ ./vendor/rails_7_gems/
RUN bundle install

# Copy application code
COPY . .

RUN useradd rails --create-home --shell /bin/bash && \
  chown -R rails:rails db log storage tmp
USER rails:rails

ENTRYPOINT ["/web-app/bin/docker-dev-entrypoint"]

EXPOSE 3000
CMD ["./bin/rails", "server", "-b", "0.0.0.0"]
`

**Comment by MSP-Greg** [comment]
Have you tried making a verified connection with net/http?  Or, bypass Bundler/RubyGems for testing to see if your env/certs are working correctly?

**Comment by RailsCod3rFuture** [comment]
I'm going to try a new approach now.

**Comment by RailsCod3rFuture** [comment]
I will layout my steps in Docker | aside: we're working on upgrading to ruby 3 after testing this release.

Dockerfile
1. Set ruby ver
