### ISSUE TITLE
openssl-master fips: Failure: test_ed25519_not_approved_on_fips(OpenSSL::TestPKey): OpenSSL::PKey::PKeyError expected but nothing was raised.

### ISSUE THREAD

**Issue by junaruga** [ruby/openssl#787]
This openssl-master fips specific failure was found on https://github.com/ruby/openssl/pull/786#issuecomment-2291460855.

The following failure happened with OpenSSL master openssl/openssl@02b8b7b83698d1c7ddfef274f16c039c8cca7988.

https://github.com/ruby/openssl/actions/runs/10405700727/job/28817053622?pr=786#step:11:103

```
1) Failure: test_ed25519_not_approved_on_fips(OpenSSL::TestPKey): OpenSSL::PKey::PKeyError expected but nothing was raised.
/home/runner/work/openssl/openssl/vendor/bundle/ruby/3.0.0/gems/test-unit-ruby-core-1.0.6/lib/core_assertions.rb:462:in `assert_raise'
/home/runner/work/openssl/openssl/test/openssl/test_pkey.rb:174:in `test_ed25519_not_approved_on_fips'
     171:     MC4CAQAwBQYDK2VwBCIEIEzNCJso/5banbbDRuwRTg9bijGfNaumJNqM9u1PuKb7
     172:     -----END PRIVATE KEY-----
     173:     EOF
  => 174:     assert_raise(OpenSSL::PKey::PKeyError) do
     175:       OpenSSL::PKey.read(priv_pem)
     176:     end
     177:   end
```

**Comment by junaruga** [comment]
The last succeeded commit is openssl/openssl@20bf3fe236d36734a17a08252ed19c9e1bc161cd according to the https://github.com/ruby/openssl/actions/runs/10261548837/job/28389492262#step:4:41

**Comment by rhenium** [comment]
There is an openssl/openssl issue/discussion: https://github.com/openssl/openssl/discussions/22054

According to the page, FIPS 140-3 *currently* allows Ed25519 and disallows X25519. But current releases of OpenSSL 3.x work the other way around?

FIPS 140 seems like a moving target, so I lean towards not checking what is "not available" in the FIPS mode.

**Comment by junaruga** [comment]
I found the openssl/openssl@5f04124aab4a477d4e58149d8f04871ff7e5ea4b causing this failure by `git bisect`.

**Comment by junaruga** [comment]
> There is an openssl/openssl issue/discussion: [openssl/openssl#22054](https://github.com/openssl/openssl/discussions/22054)
> 
> According to the page, FIPS 140-3 _currently_ allows Ed25519 and disallows X25519. But current releases of OpenSSL 3.x work the other way around?
> 
> FIPS 140 seems like a moving target, so I lean towards not checking what is "not available" in the FIPS mode.

Yes, in my understanding, FIPS 140 is a moving target. The comment https://github.com/openssl/openssl/pull/24799#issuecomment-2268918132 is about the topic as a reference.

I would agree on your opinion "I lean towards not checking what is "not available" in the FIPS mode.". Because we want to keep our tests stable. Let me send a PR about it.

**Comment by junaruga** [comment]
I sent the PR https://github.com/ruby/openssl/pull/789.
