### ISSUE TITLE
Decode ASN1 streams using IO objects

### ISSUE THREAD

**Issue by TiagoCardoso1983** [ruby/openssl#79]
I've been experimenting with `OpenSSL::ASN1` module to encode and decode SNMP PDUs. It is successful, but I have to read the stream from the socket first. 

I'm using `UDPSocket#send` and `UDPSocket#recvfrom_nonblock`, but the problem is that I don't have a way of knowing how much I have to read from the socket, as the size of the elements is encoded into the ASN1 stream, and it doesn't seem to be specified by the protocol. As it's an ASN1 stream, one could directly read from the descriptor and build the ASN tree instead of "read then decode".

This is the first time I'm using openssl directly, and I don't know if such a functionality like this exists already. I've read the documentation, and such a thing seems to exist for instances of SSLSocket, but it looks like it's only for TLS session-enabled sockets.

So, this is what I'm doing right now, in pseudo:

```ruby
socket.send pdu_request_stream, 0
..
begin
   buffer, _ = socket.recvfrom_nonblock 128
   response_stream << buffer
   response_asn = OpenSSL::ASN1.decode(response_stream)
rescue IO::WaitReadable
  socket.wait_readable(2) yada yada...
  retry
rescue OpenSSL::ASN1::ASN1Error
  # I assume the stream is not complete, so I have to process more
  retry
end
````

and this would be my "desired" solution:

```ruby
socket.send pdu_request_stream, 0
begin
   response_asn = OpenSSL::ASN1.decode_nonblock(socket)
...
```

Is a variation of this possible? Or would this be a feature request?

**Comment by rhenium** [comment]
I'm afraid I didn't get the intention of the pseudo code, as it reads only the first 128 bytes of a message and the rest will be discarded if `socket` is an UDP socket.

I thought an SNMP message is individually represented in an UDP datagram. If I understand correctly, you can read SNMP messages from an UDP socket without a special streaming support.

~~~ruby
begin
  msg, _ = socket.recvfrom_nonblock(65536)
  decoded = OpenSSL::ASN1.decode(msg)
rescue IO::WaitReadable
  ...
end
~~~

**Comment by TiagoCardoso1983** [comment]
Sorry if I didn't express my intention correctly. My intention was let SSL do the "read/decode" thing altogether. It's true that the SNMP message should not surpass the max length of an UDP datagram, although it's length may vary and the exact size of a datagram depends. Still, what is known is, SNMP PDU is represented as a BER-encoded ASN1 sequence, which means the length of each "object" is encoded into the protocol, and the most efficient way to do this would be to read the objects directly from the IO object like "get object byte; get object length; read object payload then decode". I'd like to know if `openssl` supports something like decoding from an IO object instead of a String, like `OpenSSL::ASN1.decode(udpsocket)` or ÒpenSSL::ASN1.decode(StringIO.new(encodedstring))`. It doesn't look like, however.

I've researched a bit, and found out a library that might do a variation of what I'm asking for: https://github.com/krypt/krypt/blob/master/spec/krypt-core/asn1/asn1_sequence_spec.rb#L441-L445 . However, it doesn't seem to have been updated recently, so it remains to be seen whether I could use it as a replacement.

**Comment by rhenium** [comment]
Currently OpenSSL::ASN1.decode and its existing variations don't accept IO (or pseudo-IO) objects. There are some difficulties, for example, in message-oriented transports like UDP, we must know the max packet size before calling read/recv because partial read is not possible.

While we can't know the exact size of the message, we know that the payload of an UDP datagram will be never larger than 65535 octets by specification. If you don't like the magic number, UDPSocket#recvmsg_nonblock can be used alternatively.

**Comment by tarcieri** [comment]
@TiagoCardoso1983 the Krypt decoder is still ostensibly buffering the intermediate data into a `String` as it's written in Ruby, so I don't really see the difference versus reading a UDP packet first yourself besides abstracting away the I/O operation. That isn't to say abstractions are bad, but behind the scenes it'd be doing the same IO ops and allocations

**Comment by TiagoCardoso1983** [comment]
@tarcieri are you sure about that? I've double double-checked the [krypt parsers](https://github.com/krypt/krypt-asn1-rb/tree/5d7783d65935454728c5c776f766a34f22d8745d/lib/krypt/asn1/der/parser), and it's neither buffering the datagram into a string nor using the same IO ops.

**Comment by tarcieri** [comment]
@TiagoCardoso1983 I mean, without a more specific reference I'm not sure what you're talking about, but it definitely looks to me like it's (optionally) buffering I/O (see e.g. https://github.com/krypt/krypt-asn1-rb/blob/5d7783d65935454728c5c776f766a34f22d8745d/lib/krypt/asn1/der/parser/indefinite_value_parser.rb#L12) and none of what it's doing looks like it will work out-of-the-box with UDP sockets.

**Comment by TiagoCardoso1983** [comment]
@tarcieri it seems at least to be trying to read the exact amount of data instead of reading arbitrary max UDP datagram size. The "read tag / read object length -> n / read(n) / then decode" flow seems to be more more robust, although as you said, it remains to be seen whether UDP sockets work that well with it. I'll have to have a go at testing all options. "Reading the full datagram then decode" will probably be a decent standard approach however, but how to know exactly what's the system-defined PDU size? [According to the SO thread](http://stackoverflow.com/questions/1098897/what-is-the-largest-safe-udp-packet-size-on-the-internet), people seem not to agree to a specific number.

**Comment by tarcieri** [comment]
@TiagoCardoso1983 I think with UDP you'll want to get an entire datagram, then parse it. I would expect broken behavior with any other approach.

**Comment by TiagoCardoso1983** [comment]
@tarcieri you are right, even if the buffering was a requirement of mine, it doesn't work for UDPs. I guess the OpenSSL solution is the one I'll support after all.
