### ISSUE TITLE
Skipping GitHub Pages workflow in forked repositories.

### ISSUE THREAD

**Issue by junaruga** [ruby/openssl#818]
I accidentally faced the following failure on [the GitHub Pages workflow](https://github.com/ruby/openssl/blob/master/.github/workflows/github-pages.yml) when pushing this repository's master branch to my forked repository's master branch.

https://github.com/junaruga/ruby-openssl/actions/runs/11954183436

Maybe it's better to skip the workflow in the forked repositories?

**Comment by rhenium** [comment]
It will try to publish to the GitHub Pages configured for the forked repository. For example, in my fork: https://rhenium.github.io/ruby-openssl/

It seems harmless for me.

**Comment by junaruga** [comment]
Ah, okay. Thanks for telling me that. It would be beneficial for us to try publishing the document to the GitHub page on each forked repository. Maybe I need settings to publish in my forked repository.

I would close this ticket.
