### ISSUE TITLE
OpenSSL::PKCS12::PKCS12Error: mac generation error

### ISSUE THREAD

**Issue by KratiBansal** [ruby/openssl#826]
We recently moved to openssl version 3.2.0 from 3.0.0 and during the OpenSSL::PKCS12.create method we have started receiving the following issue -

`pkcs12 = OpenSSL::PKCS12.create(        
new_resource.password,          
new_resource.key_alias,          
key,          
cert,          
[ca])            
OpenSSL::PKCS12::PKCS12Error: mac generation error
from (pry):22:in `create'`

**Comment by rhenium** [comment]
What is the openssl gem version (`OpenSSL::VERSION`) and the OpenSSL library version (`OpenSSL::OPENSSL_LIBRARY_VERSION`)?

What arguments are passed to the `OpenSSL::PKCS12.create` method? Please provide a reproducer.

**Comment by KratiBansal** [comment]
`irb(main):002:0> OpenSSL::OPENSSL_LIBRARY_VERSION
=> "OpenSSL 3.0.9 30 May 2023"
irb(main):003:0> OpenSSL::VERSION
=> "3.2.0"
irb(main):004:0> RUBY_VERSION
=> "3.1.4"`

Values passed for create -

pkcs12 = OpenSSL::PKCS12.create(
  password,
  key_alias,
  key,
  cert,
  [ca])

**Comment by MSP-Greg** [comment]
@KratiBansal

> OpenSSL::OPENSSL_LIBRARY_VERSION => "OpenSSL 3.0.9 30 May 2023"
OpenSSL::VERSION => "3.2.0"

You've built Ruby/openssl with OpenSSL 3.2.0, but you're running it with OpenSSL 3.0.9.  That may be the problem, haven't tried it myself.

**Comment by rhenium** [comment]
`OpenSSL::VERSION` tells the gem's version. Using the openssl gem 3.2.x with OpenSSL library 3.0.x is supported. The OpenSSL library version you compiled the gem with is stored in `OpenSSL::OPENSSL_VERSION`. It may be worth checking, but I suspect it would break in a different way in that case.

**Comment by MSP-Greg** [comment]
Sorry, I mixed up `OpenSSL::VERSION` and `OpenSSL::OPENSSL_VERSION`.

**Comment by KratiBansal** [comment]
> This contains very little information. Could you provide a self-contained, executable example that I can use to reproduce the error?

@rhenium That would be difficult as this is a part of a chef recipe.

`irb(main):002:0> OpenSSL::OPENSSL_VERSION
=> "OpenSSL 3.0.9 30 May 2023"
irb(main):003:0> OpenSSL::VERSION
=> "3.2.0"
irb(main):004:0> `

**Comment by KratiBansal** [comment]
@MSP-Greg can you please try reproducing the issue?

**Comment by KratiBansal** [comment]
@MSP-Greg @rhenium I was able to fix this by skipping mac verify -
`[4] pry(#<Chef::Provider::CoupaSsl>)> pkcs12 = OpenSSL::PKCS12.create(        
[4] pry(#<Chef::Provider::CoupaSsl>)*   new_resource.password,          
[4] pry(#<Chef::Provider::CoupaSsl>)*   new_resource.key_alias,          
[4] pry(#<Chef::Provider::CoupaSsl>)*   key,          
[4] pry(#<Chef::Provider::CoupaSsl>)*   cert,          
[4] pry(#<Chef::Provider::CoupaSsl>)*   [ca],          

[4] pry(#<Chef::Provider::CoupaSsl>)*   nil,           
[4] pry(#<Chef::Provider::CoupaSsl>)*   nil,           
[4] pry(#<Chef::Provider::CoupaSsl>)*   nil,           
[4] pry(#<Chef::Provider::CoupaSsl>)*   -1,          
[4] pry(#<Chef::Provider::CoupaSsl>)* nil)             
=> #<OpenSSL::PKCS12:0x00007f5eb9a462e8`

I believe we should this is due to PKCS12KDF not being FIPS approved

**Comment by rhenium** [comment]
It may not work if you're running OpenSSL in the FIPS mode.

I'm closing this for now. Without a reproducer there is little we can do to help.
