### ISSUE TITLE
Freezing client OpenSSL::SSL::SSLContext causes cert failures to silently succeed

### ISSUE THREAD

**Issue by tarcieri** [ruby/openssl#85]
## Repro

You can grab the certs this example uses [from this repo](https://github.com/socketry/socketry/tree/master/spec/support/ssl)

```ruby
require "socket"
require "pathname"
require "openssl"

ssl_server_cert = File.read("untrusted-cert.crt")
ssl_server_key  = File.read("untrusted-cert.key")

ssl_server_context = OpenSSL::SSL::SSLContext.new
ssl_server_context.cert = OpenSSL::X509::Certificate.new(ssl_server_cert)
ssl_server_context.key  = OpenSSL::PKey::RSA.new(ssl_server_key)

tcp_server = TCPServer.new("localhost", 1234)
ssl_server = OpenSSL::SSL::SSLServer.new(tcp_server, ssl_server_context)

ssl_server_thread = Thread.new { ssl_server.accept }

ssl_client_context = OpenSSL::SSL::SSLContext.new
ssl_client_context.set_params(ca_file: "trusted-ca.crt")

# Comment this out to get the expected behavior
ssl_client_context.freeze

tcp_client = TCPSocket.new("localhost", 1234)
ssl_client = OpenSSL::SSL::SSLSocket.new(tcp_client, ssl_client_context)

ssl_client.connect
p ssl_client.post_connection_check("localhost")
```

## Result

Prints `true`, indicating both that an untrusted cert was trusted and hostname verification succeeded.

Commenting out the `ssl_client_context.freeze` call results in the expected behavior.

## Expected behavior

I would either expect:

1) Raises `OpenSSL::SSL::SSLError` with `certificate verify failed`
2) Raises an exception at the time `OpenSSL::SSL::SSLContext#freeze` is called, indicating freezing SSL contexts is not allowed

I bring this up both because it's unexpected, and because it could lead to a security problem in practice

**Comment by rhenium** [comment]
SSLContext#setup which actually sets parameter to the underlying SSL_CTX is using the frozen state as a flag for "whether the context is already set up?":

https://github.com/ruby/openssl/blob/c1dd6b096f5174e1d57584e603f58a0a76a9db43/ext/openssl/ossl_ssl.c#L761

Probably we should make #freeze an alias of #setup. This will solve this issue in the 1. way.
