### ISSUE TITLE
OpenSSL::SSL::SSLSocket writes plaintext to the wire unless #connect is called

### ISSUE THREAD

**Issue by tarcieri** [ruby/openssl#9]
Repro here:

https://gist.github.com/tarcieri/b20437a1b9364d82c365

Attempting to do I/O before the SSL handshake has completed should raise an exception instead of writing plaintext to the wire.

**Comment by rhenium** [comment]
Note:
As an experiment, I disabled it but several tests outside test/openssl failed.

https://github.com/rhenium/ruby/commit/195c9ad2baebe09526b4fbc187e608acd70e946c?w=1
https://gist.github.com/rhenium/8209b06c77a877beed98895c0c803df4

Tthe code is already in the oldest version of 'OpenSSL for Ruby' I could find, but the history before 'SSLSocket' is merged into it is missing. So I still don't know why it is made so.

http://cvs.savannah.gnu.org/viewvc/ossl/ossl_ssl.c?revision=1.1&root=rubypki&sortdir=down&view=markup

**Comment by tarcieri** [comment]
@rhenium that's unfortunate :cry:

I have run into similar problems with the test suite trying to make improvements like this.

**Comment by rhenium** [comment]
Actually net/http was the only using the behavior. It has been replaced now: https://github.com/ruby/ruby/commit/4081b34d4c5da46a095c7205169ecc638fdf78ad

Since the gem also targets 2.3 for now, we can't remove it immediately, though.

**Comment by ioquatix** [comment]
+1

**Comment by jawj** [comment]
I'm not using `SSLSocket` directly, so I'm not sure. This is the code that's now broken:

```ruby
    server = TCPServer.new('0.0.0.0', port)
    ssl_server = OpenSSL::SSL::SSLServer.new(server, ssl_ctx)
    ssl_server.start_immediately = false
    client_sock = ssl_server.accept  # opens socket to client (no SSL yet)

    pg_ssl_req = client_sock.read(8)  # the Postgres SSLRequest
    if pg_ssl_req.unpack1('Q') == 3393130284026167296
      puts 'got SSLRequest message'
    else
      puts 'no SSLRequest, quitting'
      exit 1
    end

    client_sock.write('S')  # yes, we speak TLS
    client_sock = client_sock.accept  # begin handshake
    puts 'TLS connection established with client'
```

Do you know how to do raw I/O here prior to starting the TLS handshake?

For context: I had a script that was working nicely with the Mac system Ruby (version 2.6), then upgraded to 3.4 because I needed newer features in `net/imap`, and found that my script was broken.

**Comment by tarcieri** [comment]
Accept the connection as a `TCPServer`, do `client_sock.read(8)` directly on that socket, prior to involving `OpenSSL` at all.

If you determine you need to upgrade to an SSL socket, do `ssl = OpenSSL::SSL::SSLSocket.new(client_sock)` and then call `ssl.accept` to begin the handshake.

**Comment by jawj** [comment]
Many thanks for the quick replies. This works.

But I do think you might consider either adding back this feature, or otherwise documenting that it has been removed and what to do instead.
