### ISSUE TITLE
ASN1 decoding: how to ignore padding? 

### ISSUE THREAD

**Issue by TiagoCardoso1983** [ruby/openssl#91]
I'm using the ASN1 to decode information which had been previously encrypted. It was decrypted also using openssl (DES interface), and it came out padded. Let's say, for the sake of argument, the stream was ```\x02\x01\x00\x00```, where the last `\x00` is padding. I'd expect to call `ASN1.decode` and have it decode it to the integer, but instead it fails:

```ruby
pry> OpenSSL::ASN1.decode("\x02\x01\x00\x00")
OpenSSL::ASN1::ASN1Error: Type mismatch. Total bytes read: 3 Bytes available: 4 Offset: 3
from (pry):14:in `decode'
```

Is there a way to accomplish this? Or am I forced to inspect the length bytes and remove the padding myself?

**Comment by rhenium** [comment]
Because `"\x02\x01\x00\x00"` is not a valid BER encoding, it is expected that OpenSSL::ASN1.decode refuses to parse. Why do you use such a nonreversible padding?

**Comment by TiagoCardoso1983** [comment]
not exactly me, but it's the result of decrypting an SNMPv3 encrypted PDU. I'm also using openssl for the decryption, and am explicitly setting the padding to 0, as specified in the rfc. Along these lines:

```ruby
cipher = Cipher::DES.new(:CBC)
cipher.decrypt
cipher.padding = 0
cipher.key = key
cipher.iv = iv
data = cipher.update(encrypted_pdu) + cipher.final
# data was padded before encryption, so a BER-encoded PDU might have length 77, while the decrypted
# part might be length 80
# what to do here to safely remove padding before decoding?
```

And this is my question. Right now, I'm slicing all `\x00` from the resulting decrypted payload. But this is not a solution, as the last value can be a ber-encoded null, or a ber-encoded integer with value 0, and that would mess up my decoding. 

The example I gave you might not be a valid BER encoding, but I thought there could be an hidden API which would ignore bytes which aren't part of a BER-encoded sequence, and so on, like:

```ruby
stream = "0\x03\x02\x01\x00\x02\x01\x00"
OpenSSL::ASN1.decode stream
```

This will fail with a type mismatch error, but it also could just decode the sequence and ignore the subsequence integer, with, let's say, an imaginary argument `ignore_mismatches: true`.

Anyway, this is just an idea. I'd totally understand if this weren't to be supported, and would appreciate any kind of suggestions you'd have on remove padding from deciphered payloads, as I don't have currently any idea on how to do that besides the faulty patch I mentioned above.

**Comment by rhenium** [comment]
The protocol doesn't seem to give the actual content length. That's unfortunate.

I however think such an option is useful in too limited situations to provide from the openssl library.

In this case, I think you can workaround by inspecting the real content length with OpenSSL::ASN1.traverse[1]:

~~~ruby
str = "\x02\x01\x00\x00"
headerlen, bodylen = OpenSSL::ASN1.traverse(str) { |_, _, x, y, *| break x, y }
decoded = OpenSSL::ASN1.decode(str.byteslice(0, headerlen+bodylen))
~~~

[1] http://ruby.github.io/openssl/OpenSSL/ASN1.html#method-c-traverse

**Comment by TiagoCardoso1983** [comment]
The protocol does give the content length (in that case, it's an integer with size 1 and value 0, it would work the same for sequences). You need to decode it first, however. It is possible, and something that the library could do, but you know the situations in which this part of openssl is used better than me.

The workaround with traverse does seem to solve my issue. I'll have a quick try in a few minutes and will let you know. Thx for the tip!

**Comment by TiagoCardoso1983** [comment]
It did the trick. Thx Again!
