### ISSUE TITLE
DH set_key with nil public key

### ISSUE THREAD

**Issue by mfazekas** [ruby/openssl#93]
We have the following code in [net-ssh](https://github.com/net-ssh/net-ssh/blob/3f4cb5f36eae11c29137f81e99f72b3b8e9c5940/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb#L115-L124):

```ruby
      # Generate a DH key with a private key consisting of the given
      # number of bytes.
      def generate_key #:nodoc:
        dh = OpenSSL::PKey::DH.new

        dh.p, dh.g = get_parameters
        dh.priv_key = OpenSSL::BN.rand(data[:need_bytes] * 8)

        dh.generate_key! until dh.valid?

        dh
      end
```

We'd like to transform it to ```set_pqg and set_key``` unfortunately the trivial transformation does not work:

```sh
Class: <OpenSSL::PKey::PKeyError>
Message: <"DH_set0_key">
---Backtrace---
net-ssh/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:121:in `set_key'
```

The code i was trying:
```
dh.set_pqg(p, nil, g)
dh.set_key(nil, OpenSSL::BN.rand(data[:need_bytes] * 8))
```

This is the standalone ruby code we'd like to get work:
```ruby
require 'openssl'

P_s = "FFFFFFFF" "FFFFFFFF" "C90FDAA2" "2168C234" +
          "C4C6628B" "80DC1CD1" "29024E08" "8A67CC74" +
          "020BBEA6" "3B139B22" "514A0879" "8E3404DD" +
          "EF9519B3" "CD3A431B" "302B0A6D" "F25F1437" +
          "4FE1356D" "6D51C245" "E485B576" "625E7EC6" +
          "F44C42E9" "A637ED6B" "0BFF5CB6" "F406B7ED" +
          "EE386BFB" "5A899FA5" "AE9F2411" "7C4B1FE6" +
          "49286651" "ECE65381" "FFFFFFFF" "FFFFFFFF"
P_r = 16
p = OpenSSL::BN.new(P_s, P_r)
g = 2
need_bits = 256*8

dh = OpenSSL::PKey::DH.new
dh.set_pqg(p, nil, g)
dh.set_key(nil, OpenSSL::BN.rand(need_bits))

def valid?(dh)
   return false if dh.pub_key.nil? || dh.pub_key < 0
   bits_set = 0
   dh.pub_key.num_bits.times { |i| bits_set += 1 if dh.pub_key.bit_set?(i) }
   return ( bits_set > 1 && dh.pub_key < dh.p )
end

dh.generate_key! until valid?(dh)
```

**Comment by rhenium** [comment]
It is a restriction of the new OpenSSL 1.1.0 API[1]. DH#priv_key= used to access the internal structure of OpenSSL but it was made impossible. Unfortunately as far as I know there is no way to workaround except calculating the corresponding pub_key ourselves.

[1] https://www.openssl.org/docs/man1.1.0/crypto/DH_set0_key.html

By the way:

> dh.priv_key = OpenSSL::BN.rand(data[:need_bytes] * 8)
> 
> dh.generate_key! until dh.valid?

This will be infinite loop once DH#generate_key! derives an invalid pub_key.

**Comment by mfazekas** [comment]
@rhenium thanks, much for the help. 

Interesting that docs on [DH_generate_key()](https://www.openssl.org/docs/man1.1.0/crypto/DH_generate_key.html) documents that it can generate the public key, for you if private set, yet on fist set_key you need both private and public.

I've changed the construct so it first calls `DH_generate_key` and we'll only generate private key if we're not happy with what generate_key generated. This should fix the infinite loop possibility you've mentioned:

https://github.com/net-ssh/net-ssh/pull/468/files#diff-d5d20d17bb19df4a78a635b742d1b318R125
